### ISSUE TITLE
How to use the library in a browser and without package.json?

### ISSUE THREAD

**Issue by GildedHonour** [near/near-api-js#1012]
The docs assume that a web application where a library is used has to have `package.json`. That is, it's nothing but a NodeJs one, every time. There're no other languages and frameworks out there, apparently.
 
https://docs.near.org/tools/near-api-js/quick-reference#import

It's a non-sensical assumption. 

I have a web application which isn't in NodeJs and doesn't have, nor doesn't need `package.json`  And when I try to import a library into a **browser** I'll get an exception:
```
Uncaught TypeError: Failed to resolve module specifier "near-api-js". Relative references must start with either "/", "./", or "../".
```

And I see that there there're 2 tabs: "Browser/NodeJs" but this doesn't change anything because this still assums that there's `package.json` in one's web application. 

I'm tried different variations of how to include it -- none of them has worked, there've always been errors that have to do with import.  Morever, in the documentation this isn't described. 

"In case of browser - use the tab Browser" doesn't work, that is.

How to make it work?

**Comment by andy-haynes** [comment]
You can use `near-api-js` in the browser by referencing the [CDN-hosted bundle](https://www.jsdelivr.com/package/npm/near-api-js?path=dist):
```html
<script src="https://cdn.jsdelivr.net/npm/near-api-js@1.1.0/dist/near-api-js.min.js" integrity="sha256-GfSSj7AKFey273m4IVMpDwz8Kq0Auh7Gxpsw8Pi3A/4=" crossorigin="anonymous"></script>
```

Example usage [here](https://docs.near.org/develop/integrate/frontend#adding-near-api-js-and-wallet-selector).

**Comment by GildedHonour** [comment]
@andy-haynes 


(1)
```
<script src="https://cdn.jsdelivr.net/npm/near-api-js@0.44.2/dist/near-api-js.min.js" integrity="sha256-W5o4c5DRZZXMKjuL41jsaoBpE/UHMkrGvIxN9HcjNSY=" crossorigin="anonymous"></script>
<script type="text/javascript">
  import * as nearAPI from "near-api-js";
</script>
```
===>

    Uncaught SyntaxError: Cannot use import statement outside a module (at 2:187:3)


(2)

```
<script src="https://cdn.jsdelivr.net/npm/near-api-js@0.44.2/dist/near-api-js.min.js" integrity="sha256-W5o4c5DRZZXMKjuL41jsaoBpE/UHMkrGvIxN9HcjNSY=" crossorigin="anonymous"></script>
<script type="module">
  import * as nearAPI from "near-api-js";
</script>
```
===>

    Uncaught TypeError: Failed to resolve module specifier "near-api-js". Relative references must start with either "/", "./", or "../".

**Comment by andy-haynes** [comment]
The module is under `window`:

```html
<script src="https://cdn.jsdelivr.net/npm/near-api-js@0.44.2/dist/near-api-js.min.js" integrity="sha256-W5o4c5DRZZXMKjuL41jsaoBpE/UHMkrGvIxN9HcjNSY=" crossorigin="anonymous"></script>
<script type="text/javascript">
  console.log(window.nearApi);
</script>
```

**Comment by GildedHonour** [comment]
```
window.nearApi
===>
undefined
```

**Comment by andy-haynes** [comment]
I've updated my example, rules around JavaScript execution context still apply 🙂

**Comment by GildedHonour** [comment]
Ok. But that's an old version. Whereas with the latest version - `1.1.0` - it won't work because of "integrity error".  Where is the  integrity code for the latest version?

**Comment by andy-haynes** [comment]
Updated again. My post was copied from your example, which referenced the older version. You can use the [link from above](https://www.jsdelivr.com/package/npm/near-api-js?path=dist) to find the versions and their corresponding hashes (referred to there as `SRI`).

**Comment by GildedHonour** [comment]
Thx
