### ISSUE TITLE
confusing account experience: shell to wallet

### ISSUE THREAD

**Issue by amgando** [near/near-api-js#103]
not sure where to document this exactly, here or `nearprotocol/near-shell`

i started by creating a new account through NEAR Shell

 near create_account sherif3 --masterAccount=sherif

and ended up trying to recover the account via NEAR Wallet and getting <span class="error">[this error]</span>([https://github.com/nearprotocol/nearlib/blob/d8b0f397fdf6a0729d293660e3c4dda153ea314e/lib/account.js#L34](https://github.com/nearprotocol/nearlib/blob/d8b0f397fdf6a0729d293660e3c4dda153ea314e/lib/account.js#L34))

 Missing public key for sherif3 in default

 Error in background action: BadRequestError: Error: Failed to fetch access key for 'sherif3' with public key ed25519:EsjyvmBb2ESGiyjPHMBUnTGCe1P6hPjmxxY2b2hrTBAv

could mean one of:

*   i'm not supposed to do this <span class="error">[!/images/icons/emoticons/warning.png!| /images/icons/emoticons/warning.png]</span>
*   we need clearer message in NEAR Shell about how to "attach" a created account to your wallet
*   we need clearer message in NEAR Wallet about how to recover accounts created via NEAR Shell

also related to this flow, the error only appeared in the console. no SMS was sent while trying to recover and this error did not appear anywhere in the DOM. generally SMS messages were arriving for another accounts while following the same steps to recover it: sherif2\. but that account was originally created via the NEAR Wallet interface on another computer.

**Comment by trechriron** [comment]
@amgando  - Is this issue still relevant? Thanks for your time!

**Comment by vikinatora** [comment]
Closing this issue as @amgando hasn't responded.
