### ISSUE TITLE
pnpm lint does not run resulting in not being able to push anything

### ISSUE THREAD

**Issue by waynenilsen** [near/near-api-js#1032]
**Describe the bug**
pnpm lint does not run resulting in not being able to push anything

```
ERROR  workspace configuration error: package.json: no workspaces found. Turborepo requires npm workspaces to be defined in the root package.json
```

**To Reproduce**

* uninstall any globally installed pnpm and turbo installations
* checkout the main branch
* run `npm i -g pnpm` and `npm i -g turbo`
* run `pnpm lint`

**Expected behavior**
it should work

**Desktop (please complete the following information):**
 - OS: MACOS
 - Version 12.6

**Additional context**

my turbo version `1.4.5`

my pnpm version `7.16.0`

## suggested solution

the repo should install these as dev-dependancies and run them using `npx` for increased version reliability

**Comment by andy-haynes** [comment]
Hi @waynenilsen, it looks like `pnpm install` is required prior to `pnpm lint` (to pull in `concurrently`).

However the error you posted seems to indicate an issue with package resolution. Where in the project directory are you running `pnpm lint`?

**Comment by andy-haynes** [comment]
@waynenilsen  I see that another dev is seeing the same thing https://github.com/near/near-api-js/pull/1029#issuecomment-1317445500

You mention having `turbo` installed globally but it is already a dev dependency of the project root. Seems an unlikely cause but it might be worth removing the global install and trying again.

Are any other commands you've seen not working? You've run `pnpm install` and `pnpm build` without issues?

**Comment by andy-haynes** [comment]
Closing as inactive, please reopen if this is still occurring.
