### ISSUE TITLE
When building an with rollup that depends on near-api-js through wallet-selector a strange error arises at web app runtime

### ISSUE THREAD

**Issue by felixniemeyer** [near/near-api-js#1035]
**Describe the bug**
I've been developing an app using wallet-selector to handle login to NEAR and contract interactions. 
I am using Vite which uses native ESM file serving during development. 
After I build the project, which uses rollup internally and processes fine, I get an `Uncaught TypeError` when opening the web app in the browser:

in the file `account_multisig.js`

`class heritage account_1.Account is not an object or null`

![image](https://user-images.githubusercontent.com/5720176/203329379-06840cf2-790d-41dc-b6f4-b246652204fa.png)

I think this has something to do with common js 'require(...)' vs es modules and how rollup treats these. 

I'm not sure whether you can do anything about it or whether the cause lies outside of your scope. 

Maybe you have ideas what I could investigate

**Comment by felixniemeyer** [comment]
Here is some code from the transpiled account_multisig.js
```
'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Account2FA = exports.AccountMultisig = exports.MULTISIG_CONFIRM_METHODS = exports.MULTISIG_CHANGE_METHODS = exports.MULTISIG_DEPOSIT = exports.MULTISIG_GAS = exports.MULTISIG_ALLOWANCE = exports.MULTISIG_STORAGE_KEY = void 0;
const bn_js_1 = __importDefault(require("bn.js"));
const depd_1 = __importDefault(require("depd"));
const account_1 = require("./account");
const format_1 = require("./utils/format");
const key_pair_1 = require("./utils/key_pair");
```

And here the account.js 
```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Account = void 0;
...
class Account {
...
}
exports.Account = Account;
```

**Comment by kujtimprenkuSQA** [comment]
@felixniemeyer could you try having a look at this comment: https://github.com/near/wallet-selector/issues/502#issuecomment-1284158448 follow the links in the comment and I believe you will get this issue sorted.

**Comment by felixniemeyer** [comment]
Thank you for pointing me there again!
You were way ahead of me back then :sweat_smile: 

Making the recommended changes from [the post you are linking to](https://github.com/sapphi-red) to my vite config fixed it: 
```
optimizeDeps.disabled: false
build.commonjsOptions.include: []
```
