### ISSUE TITLE
Biometric package has dependency which cannot be resolved by npm and pnpm

### ISSUE THREAD

**Issue by mpeterdev** [near/near-api-js#1131]
https://github.com/near/near-api-js/blob/aa787f359d216f803fd96415cf71cbe981a35a5f/packages/biometric-ed25519/package.json#L16

Please change this to an explicit dependency

**Comment by andy-haynes** [comment]
Removing the `yarn.lock` and republishing fixed this. New version with the correct dependency is `0.0.11`
