### ISSUE TITLE
Outdated TypeDocs for near-api-js

### ISSUE THREAD

**Issue by bucanero** [near/near-api-js#1190]
### Description

The linked docs page https://near.github.io/near-api-js has old documentation, and mentions near-api-js v1.0.0

As reference, it seems that the Github pages deploy hasn't been running for about a year, since September 2022:
https://github.com/near/near-api-js/deployments/github-pages

### Optional: User Story

As a dev, I'd like to find current documentation about the JS library that I want to use to build on Near.

**Comment by vikinatora** [comment]
Resolved by #1274
