### ISSUE TITLE
The `wallet.requestSignIn` stopped working on v3.0.0

### ISSUE THREAD

**Issue by kujtimprenkuSQA** [near/near-api-js#1218]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

After the last update, it looks like the `wallet.requestSignIn(params)` functionality has been broken.

### Reproducible demo

https://github.com/kujtimprenkuSQA/simple-naj-demo

### Steps to reproduce

Visit the live demo of the above example:
> Note the demo uses CDN but same thing happens if we install the package from NPM

1 Visit: https://kujtimprenkusqa.github.io/simple-naj-demo/
2. Click `SignIn With Near` button
3. See errors on console dev tools.

The code is simple and it's all in `index.html`

The same demo can be found here too: https://jsfiddle.net/kujtimprenku/jsr3kqga/

### Expected behavior

The `wallet.requestSignIn` should redirect the user to the wallet.

### Actual behavior

An error is thrown in console:

![image](https://github.com/near/near-api-js/assets/95851345/b6ce14e4-04d4-43c6-90b1-1ebe75368343)

### Your environment

- NEAR JavaScript API version used: 3.0.0
- Frontend framework (if applicable): No framework just a simple HTML/JS file
- Relevant dependencies (if applicable): n/a

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by vikinatora** [comment]
Hey, thanks for the report. We're working on it, should have the PR tomorrow.

**Comment by vikinatora** [comment]
@kujtimprenkuSQA should be resolved with v3.0.1
