### ISSUE TITLE
Gracefully handle RPC timeout during transaction confirmation

### ISSUE THREAD

**Issue by kcole16** [near/near-api-js#127]
Currently, when the network is slow and RPC times out during transaction confirmation, the end result is an error message, with no indication or whether or not the transaction was successful.

See [#258 in near-wallet](https://github.com/nearprotocol/near-wallet/issues/258) for a related error.

**Comment by kcole16** [comment]
@bowenwang1996 Will RPC still return the TX hash in the case of a timeout?

**Comment by bowenwang1996** [comment]
Right now it doesn't but it is pretty easy to make it return the tx hash.

**Comment by kcole16** [comment]
@vgrichina @janedegtiareva Thoughts on this?

**Comment by vgrichina** [comment]
nearlib can returned transaction hash and signed transaction in error. Then caller can chose to retry  / monitor status of transaction depending on situation.
