### ISSUE TITLE
Error: Unable to resolve module http from ./node_modules/@near-js/providers/lib/fetch.js http could not be found within the project

### ISSUE THREAD

**Issue by Pawel-Szydlo** [near/near-api-js#1272]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

I am creating a mobile application in react native. I updated near-api-js to the latest version 3.0.2 and got this error.
Has anyone had a similar problem?

### Steps to reproduce

1. near-api-js update from 0.44 to 3.0.2

### Expected behavior

Not to throw an error

### Actual behavior

![image](https://github.com/near/near-api-js/assets/89639506/aba68901-3b8d-4dca-b635-0fa7b0bab6e0)

### Your environment

- NEAR JavaScript API version used: 3.0.2
- Frontend framework (if applicable): react-native 0.72
- Relevant dependencies (if applicable):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by vikinatora** [comment]
Hey @Pawel-Szydlo, you've made a significant version upgrade - from version 0 to 3. As per any major version, there are breaking changes. Could you please switch to v2.1.4 and see if it resolves the issue?

**Comment by vikinatora** [comment]
@Pawel-Szydlo, closing the issue as no more info is provided and issue couldn't be reproduced
