### ISSUE TITLE
Support nearcore 1.37

### ISSUE THREAD

**Issue by telezhnaya** [near/near-api-js#1285]
We need to adapt to changed RPC methods and potentially start using the new ones. 

More details: https://github.com/near/nearcore/blob/447572bb775a5954ca7a5a4b65c85b45aab9e499/chain/jsonrpc/CHANGELOG.md#023
Copy-pasting the most important parts here

> Added send_tx method which gives configurable execution guarantees options and potentially replaces existing broadcast_tx_async, broadcast_tx_commit
> Field final_execution_status is presented in the response of methods tx, EXPERIMENTAL_tx_status, broadcast_tx_commit, send_tx
> Allowed use json in request for methods EXPERIMENTAL_tx_status, tx, broadcast_tx_commit, broadcast_tx_async, send_tx
> Parameter wait_until (same entity as final_execution_status in the response) is presented as optional request parameter for methods EXPERIMENTAL_tx_status, tx, send_tx. The response will be returned only when the desired level of finality is reached
> Breaking changes
> 
> Removed EXPERIMENTAL_check_tx method. Use tx method instead
> Removed EXPERIMENTAL_broadcast_tx_sync method. Use send_tx method instead

The nearcore updates timeline: https://github.com/near/nearcore/issues/10404

**Comment by vikinatora** [comment]
Resolved by #1317
