### ISSUE TITLE
 [Error] createAccount don't work on testnet.

### ISSUE THREAD

**Issue by KimCookieYa** [near/near-api-js#1290]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

![image](https://github.com/near/near-api-js/assets/45006957/ea4bd5bc-a890-458e-a74d-5e2497021f50)

[packages/cookbook/accounts/create-testnet-account.js](https://github.com/near/near-api-js/blob/master/packages/cookbook/accounts/create-testnet-account.js)

I copied it while looking at the cookbook of near-api-js. The only difference is that I used BrowserLocalStorageKeyStore because it's being developed with Chrome extension application. Why do I get an error when I check that the key is saved to localstorage?

```
Account creation failed: Error: no matching key pair found in InMemorySigner([object Object])
    at Account.<anonymous> (index.js:19540:19)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:19409:28)
```

```javascript
import { utils, keyStores, KeyPair, connect, providers } from 'near-api-js';

const myKeyStore = new keyStores.BrowserLocalStorageKeyStore();

const config = {
  networkId: 'testnet',
  keyStore: myKeyStore,
  nodeUrl: 'https://rpc.testnet.near.org',
  walletUrl: 'https://testnet.mynearwallet.com/',
  helperUrl: 'https://helper.testnet.near.org',
};

export async function createNearAccount(creatprAccountId: string, newAccountId: string, amount: string) {
  const near = await connect(config);
  const creatorAccount = await near.account(creatprAccountId);
  const keyPair = KeyPair.fromRandom('ed25519');
  const publicKey = keyPair.getPublicKey().toString();

  await myKeyStore.setKey(config.networkId, newAccountId, keyPair);
  try {
    await creatorAccount.createAccount(newAccountId, publicKey, utils.format.parseNearAmount(amount));
    console.log('Account creation successful');
    return true;
  } catch (error) {
    console.error('Account creation failed:', error);
    return false;
  }
}```

### Reproducible demo

https://github.com/2024-Circular-Reference/near-wallet-test

### Steps to reproduce

1. git clone https://github.com/2024-Circular-Reference/near-wallet-test
2. pnpm install
3. pnpm dev or npm run dev
4. Open in browser - chrome://extensions
5. Check - Developer mode
6. Find and Click - Load unpacked extension
7. Select - dist folder
8. Click - "Near Wallet with ZK&DID" in chrome extension
9. Click - "Submit" button"
10. Check - "console" tab in DevTools

### Expected behavior

A message should be output stating that the sub-account 'test.kimcookieya.testnet' has been created.

### Actual behavior

![image](https://github.com/near/near-api-js/assets/45006957/ea4bd5bc-a890-458e-a74d-5e2497021f50)

I copied it while looking at the cookbook of near-api-js. The only difference is that I used BrowserLocalStorageKeyStore because it's being developed with Chrome extension application. Why do I get an error when I check that the key is saved to localstorage?

```
Account creation failed: Error: no matching key pair found in InMemorySigner([object Object])
    at Account.<anonymous> (index.js:19540:19)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:19409:28)
```

### Your environment

- NEAR JavaScript API version used: ^3.0.2
- Frontend framework (if applicable): React & Chrome Extension
- Relevant dependencies (if applicable):


### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by vikinatora** [comment]
Hey @KimCookieYa, I did the steps to reproduce the example and I didn't receive any error. What OS are you using?
<img width="318" alt="image" src="https://github.com/near/near-api-js/assets/29047760/873c4342-3652-4ab8-82e7-747566f83100">

**Comment by vikinatora** [comment]
@KimCookieYa If you use the native function `createAccount` instead of doing it manually, the code works. Please use the following snippet and let me know if it worked for you. 
```
export async function createNearAccount(creatprAccountId: string, newAccountId: string, amount: string) {
  const near = await connect(config);
  const keyPair = KeyPair.fromRandom('ed25519');
  const publicKey = keyPair.getPublicKey();

  await myKeyStore.setKey(config.networkId, newAccountId, keyPair);
  try {
    const account = await near.createAccount(newAccountId, publicKey);
    console.log('account:', account);
    // await creatorAccount.createAccount(newAccountId, publicKey, utils.format.parseNearAmount(amount));
    // const res = await creatorAccount.functionCall({
    //   contractId: config.networkId,
    //   methodName: 'create_account',
    //   args: {
    //     new_account_id: newAccountId,
    //     new_public_key: publicKey,
    //   },
    //   gas: '300000000000000',
    //   attachedDeposit: utils.format.parseNearAmount(amount),

    // });
    console.log('Account creation successful');
    return true;
  } catch (error) {
    console.error('Account creation failed:', error);
    return false;
  }
}

```

**Comment by KimCookieYa** [comment]
My OS is Windows 11 & Chrome(latest)

I solved it thanks to the code you gave me! But I'm curious, can I create a new account without a creator account? Is it only possible on testnet?

**Comment by vikinatora** [comment]
You can find Details about account creation [here](https://docs.near.org/concepts/basics/accounts/creating-accounts). Testnet and Mainnet behave the same way.

**Comment by KimCookieYa** [comment]
Isn't the link a way to create an account on the local testnet? What I'm wondering is if "near-cli" can make a named account on a real testnet, not a local testnet.

Please let me know if I know anything strange!

**Comment by KimCookieYa** [comment]
oh, Sorry....  Using ```near.createAccount('kimcookieya.testnet)```, I checked that the account was created well even in the actual testnet. I thought I would get an error if I tried to create an existing account once more, but the response came back well, so I thought testnet was separate from the local environment and the actual environment.

In "NearBlocks", I found that the batch transaction failed while continuing with "kimcookieya.testnet"...

![image](https://github.com/near/near-api-js/assets/45006957/e59056d0-f689-4e74-9422-f0e76b7cffc0)

**Comment by vikinatora** [comment]
These batch transactions try to create your account. Since you [already have created the account](https://testnet.nearblocks.io/txns/AV4ZoT25DvtyUv7kjjVFMe74VTPdZ6L8mcvhQWPUgPJe), it makes sense for them to fail.

**Comment by KimCookieYa** [comment]
Thank you for your help!! I'll leave another issue if I have any questions
