### ISSUE TITLE
Biometric createKey failing with Bitwarden password manager "expected ‘id’ or ‘rawId’ field"

### ISSUE THREAD

**Issue by SurgeCode** [near/near-api-js#1330]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

When calling the createKey() method with the Bitwarden password manager extension that uses passkey the crendetials Id seems to have an incorrect format causing an error

![telegram-cloud-photo-size-4-5796583529239396695-y](https://github.com/near/near-api-js/assets/52105707/be620b13-06d3-4981-a9c8-7c03d2cadbc6)

On the left side you see a working payload that contains an ArrayBuffer and on the right side a Uint8Array

### Steps to reproduce

1.  [Install bitwarden password manager extension](https://chromewebstore.google.com/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb)
2. Call `createKey()` method

### Expected behavior

Create key should not throw an error

### Actual behavior

“Error: Type error: expected ‘id’ or ‘rawId’ field of request to be ArrayBuffer, got rawId object and id string”

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by hcho112** [comment]
Hello @SurgeCode thank you for reporting this. 
So I have conduct a small experiment on this in my local environment and try to focus on the error message: `Error: Type error: expected ‘id’ or ‘rawId’ field of request to be ArrayBuffer, got rawId object and id string`

### The ones that are currently working:
- Default Chrome passkey:
<img width="2245" alt="default passkey" src="https://github.com/near/near-api-js/assets/6027014/4be9bb05-6146-4658-8217-555267c2a713">

- 1Password (password management tool) on Chrome:
<img width="2580" alt="1password" src="https://github.com/near/near-api-js/assets/6027014/b898d448-882e-43dd-8789-5da016878ce0">

There is slight difference, but we can see that `rawId` is in `ArrayBuffer`

### Not working:
- Bitwarden on Chrome:
<img width="2940" alt="bitwarden" src="https://github.com/near/near-api-js/assets/6027014/91c638ec-5c46-4a5c-933f-6dcb7bbd9f5f">

In here, 'rawId' is in `Uint8Array` format where it aligns with error message. So I have taken the investigation further and see what it should be:
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/rawId
In terms of definition, it is expecting `ArrayBuffer` NOT `Uint8Array`.

So at this point, Bitwarden is mutating the format that is set by [W3C standard](https://www.w3.org/TR/webauthn-2/#iface-pkcredential). 

I will continue to seek for solution on getting Bitwarden working by injecting a thin logic to re-construct fido2 friendly format

**Comment by hcho112** [comment]
Progress update: I manage to get the creation working via data format conversion. However using them to sign in isn't working with no error.
(1Password works with signin flow as well)

Will continue investigate the issue on sign in..

**Comment by hcho112** [comment]
I have created PR for the solution. Basically Bitwarden converts some of the properties from `ArrayBuffer` to `Uint8Array` and it was simple enough to convert them back. 

Once this PR gets merged and deployed, then I will update `fast-auth-signer` package with latest version and from there, it should work as expected. 

Will continue to update on this PR

**Comment by hcho112** [comment]
If you are using [@near-js/biometric-ed25519](https://www.npmjs.com/package/@near-js/biometric-ed25519) directly, please update the version number to `1.1.2` and try above issue again. If it is not fixed, please let me know. (If it works for you, please also leave a comment here if then, will lose this issue)

We will also aim to update `fast-auth-signer` soon.

**Comment by vikinatora** [comment]
@SurgeCode we just release a new version of biometric package(`@near-js/biometric-ed25519@1.2.1`). Can you see if this issue is resolved?

**Comment by hcho112** [comment]
Since there was no further feedback, will close this ticket.
