### ISSUE TITLE
Error sending signed transaction with v4.0.3

### ISSUE THREAD

**Issue by paouvrard** [near/near-api-js#1371]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [ ] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [x] I have read the console error messages carefully (if applicable).

### Description

Sending a signed transaction with naj v4.0.3 gives the error `Expected string not undefined(undefined) at value.signerId`.

The issue appears to come from this instance check during encodeTransaction:
- https://github.com/near/near-api-js/blob/9d86917d103a855666ebec17b0d839a937a3e1b3/packages/providers/src/json-rpc-provider.ts#L115
- https://github.com/near/near-api-js/blob/9d86917d103a855666ebec17b0d839a937a3e1b3/packages/transactions/src/schema.ts#L40

v4.0.2 doesn't have this issue.

Looking at the v4.0.2 release, it contains all the packages published: https://github.com/near/near-api-js/commit/d76a49756cd2fb250da58aaa5a9dca84a6566706
But looking at the v4.0.3, not all the packages have been published: https://github.com/near/near-api-js/commit/710f72d3e3af98d8692354053e5d0a44adaca361 which I think causes the instance check bug.
So making a v4.0.4 release of all the packages should solve the issue.

### Reproducible demo

https://near.github.io/wallet-selector/

### Steps to reproduce

Visit the wallet selector guestbook demo https://near.github.io/wallet-selector/ (https://github.com/near/wallet-selector)
Connect a wallet like Meteor or MNW
Type a message
Click Sign

This will create and sign a LAK transaction but fail to encode it before sending.

### Expected behavior

Encode and send the signed transaction.

### Actual behavior

Error during encodeTransaction.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by bh2smith** [comment]
You need to provide the signerId (named account) in the payload.

**Comment by paouvrard** [comment]
> You need to provide the signerId (named account) in the payload.

I don't think that is the problem, this is the SignedTransaction [schema](https://github.com/near/near-api-js/blob/9d86917d103a855666ebec17b0d839a937a3e1b3/packages/transactions/src/schema.ts#L244) and my object does have a signerId.
I think the instanceof check mistakenly uses the Transaction schema.
If I manually encode and send the same payload it works:
```
const bytes = encodeTransaction(signedTransaction);
const nearTx: FinalExecutionOutcome = await provider.sendJsonRpc(
    "send_tx",
    {
        signed_tx_base64: Buffer.from(bytes).toString("base64"),
        wait_until: "EXECUTED_OPTIMISTIC",
    }
);
```

**Comment by bh2smith** [comment]
Ah so perhaps the error message is just incorrect... `Expected string not undefined(undefined) at value.signerId.` could it be something with your byte encoding that its misinterpreting?

**Comment by andy-haynes** [comment]
> So making a v4.0.4 release of all the packages should solve the issue.

Not every NPM publish affects all packages - unchanged packages do not get a version bump. `near-api-js@4.0.3` was a patch bump so that the `encodeTransaction` function could be imported from `near-api-js` directly; no other packages were involved with this change.

> The issue appears to come from this instance check during encodeTransaction

The code you reference predates the 4.0.0 release. I don't see how this could have changed between 4.0.2 and 4.0.3.

The immediate issue appears to be that the guest book requires a nonzero deposit value: https://github.com/Meteor-Wallet/meteor-public/issues/25

**Comment by paouvrard** [comment]
> near-api-js@4.0.3 was a patch bump so that the encodeTransaction function would be exported from near-api-js...

Thank you for clarifying.

> The immediate issue appears to be that the guest book requires a nonzero deposit value

Limited Access Key transactions are also supported (zero deposit).

Diving deeper into the wallet-selector's yarn.lock I see that the @mintbase-js/wallet is importing naj v3 which appears to cause this issue because removing it from the project solved the problem.
