### ISSUE TITLE
NEAR amounts formatting for corner cases

### ISSUE THREAD

**Issue by frol** [near/near-api-js#157]
I would like to bring an issue of presenting NEAR amounts that are small or can be rounded incorrectly.

Here are the test cases:

* 1 yoctoNEAR is currently formatted as 0 NEAR; There are two better ways to format 1yoctoNEAR (I believe both are useful in different contexts):
  * 1 yoctoNEAR / 1 yN
  * <0.00001 N / "less than 0.00001 N"
* 999999999999999999999999 yN is rounded to 1 N. It is hard to find the best way to present this value, but here is my take:
  * "almost 1 N"
  * "0.999999 .. 1 N"
  * "1 N without 1 yN" :confused: 

*Ref https://github.com/nearprotocol/near-explorer/issues/152*

**Comment by janedegtiareva** [comment]
* We need to design how this shows up in UI 
@frol do you mind providing some specific requirements for near-api-js?

**Comment by frol** [comment]
The main requirement is to display any amounts of NEAR in a human-readable format no matter how small or how huge the value is, we should just use all the metric prefixes, so the number is always less than 1000 and greater or equal than 1:

* 1 NEAR (N)
* 999.99 milliNEAR (mN)
* 1 yoctoNEAR (yN)
* 999 yoctoNEAR (yN)
* 1 zeptoNEAR (zN) [1000 yoctoNEAR]
* 1 kiloNEAR (kN) [1000 NEAR]

We should not round the amounts up, so 9,999,999,999 yN should be 9.99 femtoNEAR, thus we need to indicate that there is some more tokens, e.g. 9.99+ fN or 9.99~ fN.

In Explorer, we display the balances, transfers, and fees, so the amounts of tokens we need to display can be both huge and small.

**Comment by amgando** [comment]
> _The main requirement is to display any amounts of NEAR in a human-readable format_

As far as user interfaces go (wallet, shell, explorer, etc) i suggest we round things off to simple values of NEAR because that's what humans are expecting (you have ~$1, not $1.00000000001).  The API should surface the exact number along with a human readable value.  The UI can show the human readable value with the exact number showing up as a tooltip (or similar hidden-before-reveal container)

**Comment by volovyk-s** [comment]
Looks like we have a flexible way to format `N` amount here:
https://github.com/near/near-api-js/blob/master/src/utils/format.ts
@frol if you feel like we need something more specific - feel free to reopen this issue.
