### ISSUE TITLE
Keystore should also expose encryption/decryption 

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-api-js#175]
Right now keystore only has message signing and signature verification but doesn't have anything related to encryption/decryption.

**Comment by janedegtiareva** [comment]
@bowenwang1996 is there a customer use case for this? It would be helpful in order to assign priority properly.

**Comment by bowenwang1996** [comment]
@janedegtiareva I think we just asked people to use tweenacl directly, so not very urgent.

**Comment by abacabadabacaba** [comment]
NEAR client libraries are for working with NEAR. Developers needing encryption/decryption should use a different library designed for that.
We shouldn't use NEAR account keys for things other than signing transactions, see nearprotocol/nearcore#2833.
