### ISSUE TITLE
Return error during requestSignIn if contractId is invalid

### ISSUE THREAD

**Issue by kcole16** [near/near-api-js#195]
Similar to https://github.com/nearprotocol/near-wallet/issues/219.

**Expected behavior**
When entering an invalid (non-existent) `contractId` argument in `nearlib.WalletAccount.requestSignIn`, the developer should receive an error.

**Comment by potatodepaulo** [comment]
@kcole16 is this just in wallet? Is this solved? Not really sure how to fix this on near-api-js side right now.

**Comment by kcole16** [comment]
We've implemented a fix on the wallet side, but I do think we should generalize this somewhere, as this is really an error on the app developer's side and could occur with any wallet.
