### ISSUE TITLE
Expose `changes` RPC API

### ISSUE THREAD

**Issue by frol** [near/near-api-js#196]
We have recently added (https://github.com/nearprotocol/nearcore/pull/1910) a new RPC API method: `changes`.

Read more here: https://github.com/nearprotocol/docs/issues/173

**Comment by nearmax** [comment]
@kcole16 What is the priority on this issue? Flux needs it.

**Comment by vgrichina** [comment]
@nearmax Flux can already call it as following:

```
near.connection.provider.sendJsonRpc('changes', [block_hash, { changes_type, changes_type_name,  account_id, key_prefix }]);
```

we can make it more explicit that it's possible by making `sendJsonRpc` non-private

**Comment by vgrichina** [comment]
Moving to `P3` as it shouldn't be a blocker (it's trivial to do the query without special support).

**Comment by mehtaphysical** [comment]
This was added in #534
