### ISSUE TITLE
nearlib sometimes sends 2 txns with the same nonce at once. 1 is guaranteed to fail.

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-api-js#205]
This can be addressed by making there is a singleton connection and cache the nonce (e.g. in local storage).

**Comment by evgenykuzyakov** [comment]
It seems to be triggered when the access key points to its own account. We've tried to repro with the studio app, but it doesn't reproduce correctly.

**Comment by evgenykuzyakov** [comment]
Can we prioritize the fix?
Currently the accessKey is always pulled from the node through RPC. It doesn't cache the key locally:
https://github.com/nearprotocol/nearlib/blob/master/src.ts/account.ts#L91-L100

**Comment by evgenykuzyakov** [comment]
Background: Right now 2 of the apps I'm working on (ethrelay and metanear) can't send more than 1 transaction per second. So I have to implement queue for metanear and to reimplement sendTransaction

**Comment by evgenykuzyakov** [comment]
> Getting cors error: 
Access to fetch at 'https://rpc.nearprotocol.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
const nearRpc = new providers.JsonRpcProvider("https://rpc.nearprotocol.com");
return await nearRpc.sendJsonRpc('tx', [txHash, accountId]);
```
txHash is encoded and accountId is also expected val

<img width="777" alt="Screen Shot 2020-03-30 at 9 56 16 AM" src="https://user-images.githubusercontent.com/470453/77939924-b8c25780-726c-11ea-997c-e260d6b9c705.png">

**Comment by vgrichina** [comment]
@evgenykuzyakov is nearcore executing OPTIONS requests as actual JSON-RPC? Not sure why would CORS error occur because of nonce error otherwise. Or is the problem that `Access-Control-Allow-Origin` isn't set on errors by nearcore?

**Comment by mikedotexe** [comment]
Moved it to **In Progress** as I understand Vlad is working on this currently.

**Comment by vgrichina** [comment]
For now this is somewhat blocked by the fact that nearcore sometimes doesn't return error specific to duplicate nonce (Timeout is returned instead).

**Comment by bowenwang1996** [comment]
nearcore issue: https://github.com/nearprotocol/nearcore/issues/2039.
