### ISSUE TITLE
After switching ENV unclear why keys don't work

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#209]
Setting `NODE_ENV=local` leads to the `neardev/default` keys stop working. But it's also super unclear that have happened. It just says that there is no key, but doesn't actually show the path it looks for them.

**Comment by potatodepaulo** [comment]
Expected behavior: When you change environments, there is a clear way to change keys. If there are no keys that can be used, then the user should be notified.

**Comment by janedegtiareva** [comment]
This is a duplicate of https://github.com/near/near-shell/issues/340

**Comment by vikinatora** [comment]
Hi @ilblackdragon, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this issue seems no longer relevant. Please let me know if that's not the case; otherwise, I'll proceed to close the issue in 5 days.

**Comment by ilblackdragon** [comment]
No longer relevant.
