### ISSUE TITLE
Suggestion: update Provider method name from txStatus to tx

### ISSUE THREAD

**Issue by barbaraliau** [near/near-api-js#219]
`txStatus` returns more than just the transaction status, and updating its name to `tx` would reflect that, as well as maintain consistency with other similar methods that retrieve information (e.g. `block`, `chunk`). 

This method would also provide consistency with the `JsonRpcProvider` method `tx`.

```ts
 export declare abstract class Provider 

 { abstract getNetwork(): Promise<Network>; abstract status(): Promise<NodeStatusResult>; abstract sendTransaction(signedTransaction: SignedTransaction): Promise<FinalExecutionOutcome>; abstract txStatus(txHash: Uint8Array, accountId: string): Promise<FinalExecutionOutcome>; abstract query(path: string, data: string): Promise<any>; abstract block(blockId: BlockId): Promise<BlockResult>; abstract chunk(chunkId: ChunkId): Promise<ChunkResult>; } 

```

**Comment by vikinatora** [comment]
Hi @barbaraliau, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this issue seems no longer relevant. Please let me know if that's not the case; otherwise, I'll proceed to close the issue in 5 days.

**Comment by vikinatora** [comment]
Closing as issue isn't relevant anymore.
