### ISSUE TITLE
Nonce type inconsistency.

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-api-js#220]
When constructing a transaction we pass `nonce` as a `number` but when decoding the type of `nonce` becomes `BN` since `number` doesn't actually cover `u64`. It would be nice if the type of `nonce` is consistent on both end.

Decision: update type to a string. Add deprecation warning. [Daryl Collins](https://nearinc.atlassian.net/secure/ViewProfile.jspa?accountId=6139108a24ba8b00701167be)

**Comment by vgrichina** [comment]
I think it's bigger issue generally – basically almost every place that takes `BN` usually also allows `number` and `string`. We should formalize it by introducing `BNLike` type or smth like that and making sure conversion always happens without precision loss.
