### ISSUE TITLE
Report errors from near-api-js

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#25]
@evgenykuzyakov commented on <span class="error">[Thu Feb 21 2019]</span>([https://github.com/nearprotocol/nearcore/issues/604](https://github.com/nearprotocol/nearcore/issues/604))

—

@vgrichina commented on <span class="error">[Thu Feb 21 2019]</span>([https://github.com/nearprotocol/nearcore/issues/604#issuecomment-466236430](https://github.com/nearprotocol/nearcore/issues/604#issuecomment-466236430))

It's better to use specialized tool like [https://sentry.io/](https://sentry.io/)

—

@evgenykuzyakov commented on <span class="error">[Thu Feb 21 2019]</span>([https://github.com/nearprotocol/nearcore/issues/604#issuecomment-466262096](https://github.com/nearprotocol/nearcore/issues/604#issuecomment-466262096))

Nice. Whatever is better, let's add it.

**Comment by mikedotexe** [comment]
Suggestion to use Mixpanel as that's being added to `near-shell`
