### ISSUE TITLE
External provider injection support/standard

### ISSUE THREAD

**Issue by kcole16** [near/near-api-js#259]
1.  1.  1.  Overview
             Nearlib should support an injected "provider" or signer, in order to enable in-app transaction signing by third party wallets. This is especially relevant for mobile wallets with browsers and chrome extensions.

We also need a pattern to easily allow apps to support multiple methods of signing, with NEAR Wallet as the fallback (if no injected provider). For example, the way <span class="error">[web3.js]</span>([https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#givenprovider](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#givenprovider)) handles providers.

<span class="error">[Ethereum JS Provider API Standard ]</span>([https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md))

**Comment by kcole16** [comment]
@vgrichina Thoughts on how best to do this? Wondering if we should also have a NEP for the Provider API.

**Comment by amgando** [comment]
@vgrichina is this already supported bc your work integrating Ledger?
