### ISSUE TITLE
Test nearlib and wallet integration

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#26]
@vgrichina commented on [Thu Feb 14 2019](https://github.com/nearprotocol/nearcore/issues/573)

Need to use real browser, e.g. through https://github.com/GoogleChrome/puppeteer

---

@evgenykuzyakov commented on [Tue Mar 12 2019](https://github.com/nearprotocol/nearcore/issues/573#issuecomment-472104250)

@azban I think you are already working on this. 

---

@azban commented on [Tue Mar 12 2019](https://github.com/nearprotocol/nearcore/issues/573#issuecomment-472187185)

this is done here.. i need to integrate this into CI tho. https://github.com/nearprotocol/integration/blob/master/integration/tests/integration/test_integration.py#L52

**Comment by chadoh** [comment]
Addressed by nearprotocol/nearcore#573
