### ISSUE TITLE
Expose `genesis_config` and `genesis_records` RPC API

### ISSUE THREAD

**Issue by frol** [near/near-api-js#271]
We have recently added (nearprotocol/nearcore#2109) new RPC API methods: genesis_config and genesis_records (with `EXPERIMENTAL_` prefix).

The API documentation is currently defined in the PR description mentioned above.

**Comment by Rishabhraghwendra18** [comment]
Hi @frol . Is this issue still open ?

**Comment by frol** [comment]
Nope, these methods are already implemented:

https://github.com/near/near-api-js/blob/5c2ea7b41e9be97394ccf15ef7926c592904fa82/src/providers/json-rpc-provider.ts#L201-L220

(well, `genesis_records` endpoint was removed from the JSON RPC implementation on nearcore side)
