### ISSUE TITLE
Wrap u64/u128 values with BN (big number type)

### ISSUE THREAD

**Issue by frol** [near/near-api-js#273]
There are plenty of big numbers represented as strings in nearcore RPC since JS does not support big integer types (u64, u128), but there are also many numbers currently incorrectly represented as JS numbers (I consider it to be a major bug in nearcore RPC, which has to be fixed before mainnet).

It makes a lot of sense to expose these values as big numbers. It is going to be a breaking change from the API point of view, but it is a required one since currently, the API is not user-friendly, and also may lead to bugs when the values are too big to fit into JS number type.

**Comment by vgrichina** [comment]
> but there are also many numbers currently incorrectly represented as JS numbers (I consider it to be a major bug in nearcore RPC, which has to be fixed before mainnet).

this one I completely agree with

> It makes a lot of sense to expose these values as big numbers. 

this one I think we shouldn't do. This messes up with some stuff you normally take for granted in JS (e.g. JSON roundtrip) + locks users to using specific big number library. It's not clear at all whether we should settle on `BN`, especially given that native big number support is landing into browsers, just not having full coverage yet (https://caniuse.com/#feat=bigint basically just waiting for Safari and Opera).

**Comment by frol** [comment]
Given this is a syntax extension and there is no way I can imagine a polyfill can be implemented, and we need to wait at least a few years for users to get adopted the versions of the browser that supports BigInt, it is not realistic to wait for that. Having stringly-typed numbers is not really helpful, but at least that would hold a correct value.

**Comment by vgrichina** [comment]
we for sure shouldn't wait for BigInt (don't think it's few years, Safari codebase seem to have it behind compile flag), but I think it is reasonable to just roll with strings before that. It is human readable and JSONable in a trivial way.

**Comment by frol** [comment]
What do you think about backwards compatibility? The only way I see it working is introducing duplicate fields with some suffix like _bigint while still keeping the old integers. Do you have better ideas?

**Comment by willemneal** [comment]
Why not use something like: https://github.com/peterolson/BigInteger.js/ as a polyfill?

**Comment by janedegtiareva** [comment]
Removing "good first issue" tag based on the fact that it's unclear what needs to be done
