### ISSUE TITLE
error message balance not enough doesn't seem to apply template

### ISSUE THREAD

**Issue by ailisp** [near/near-api-js#275]
I get this error when try create some account:
```
Sender abase_near18 does not have enough balance {} for operation costing {}
```

Seems `{}` above is template but they're not filled with actual numbers

**Comment by icerove** [comment]
@ailisp reproduce to see whether it is still existing.

**Comment by volovyk-s** [comment]
Already fixed, the current message is:
`Sender acc.testnet does not have enough balance 31889583289078432800000000 for operation costing 100000086184677687500000000`
