### ISSUE TITLE
config type is any

### ISSUE THREAD

**Issue by willemneal** [near/near-api-js#277]
Currently the main config value needed to connect is typed as `any`.

```ts
export class Near {
    readonly config: any;
    readonly connection: Connection;
    readonly accountCreator: AccountCreator;

    constructor(config: any) {
```

I assume this was for expediency, but do we now have an accepted shape of the config?

**Comment by vgrichina** [comment]
@willemneal whole library originally was JS. Probably good idea to add these when adding more documentation.

**Comment by amgando** [comment]
similar to #278 as related to "improving TypeScript compatibility"

**Comment by mehtaphysical** [comment]
This has been addressed :).
