### ISSUE TITLE
Fix hardcoded getNetwork to return current net

### ISSUE THREAD

**Issue by mikedotexe** [near/near-api-js#282]
https://github.com/near/near-api-js/blob/master/src/providers/json-rpc-provider.ts#L26-L35

```
async getNetwork(): Promise<Network> {
        return {
            name: 'test',
            chainId: 'test'
        };
```

With other nets like betanet coming on, seems like we need a way to determine this. I see there's a `url` available but parsing that is probably not the best approach.

**Comment by vgrichina** [comment]
@mikedotexe let's reserve Priority 0 for stuff that is actually broken in production.

For this method it's not even clear we should keep it at all. I think it's reasonable to assume no-one uses it (as this is not matching `networkId` as we use it in other places).
