### ISSUE TITLE
Update rpc_errors_schema to add Wasmer Traps 

### ISSUE THREAD

**Issue by chain-police** [near/near-api-js#294]
https://github.com/nearprotocol/nearcore/pull/2505 introduces new errors in https://raw.githubusercontent.com/nearprotocol/nearcore/d566583d6359175ff274ecbd72c634557f9fd3dc/chain/jsonrpc/res/rpc_errors_schema.json

**Comment by vgrichina** [comment]
See https://github.com/near/near-api-js/issues/331, I think we need to reduce dependency on fixed schema

**Comment by volovyk-s** [comment]
We are moving away from this architecture, all autogenerated errors will be deleted soon, closing this issue.
