### ISSUE TITLE
Validator RPC and utils

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#297]
We want to have validator tools available for all users: shell, explorer, applications.

Specifically:
 - [x] RPC to fetch validator data ([done](https://github.com/near/near-api-js/blob/ba55451c4c79d337796339d01ab40d634330556f/src/providers/json-rpc-provider.ts#L135-L142))
 - [x] Computing seat price ([done](https://github.com/near/near-api-js/blob/ba55451c4c79d337796339d01ab40d634330556f/src/validators.ts#L6-L37))
 - [ ] Computing validator schedule for any epoch (requires reimplemented random shuffle from nearcore)
 - [x] Given current validators and proposals, perspective next epoch ([done](https://github.com/near/near-api-js/blob/ba55451c4c79d337796339d01ab40d634330556f/src/validators.ts#L50-L65))

See these comments for more details:
and https://github.com/nearprotocol/nearcore/issues/2259#issuecomment-605499982 and this PR for code: 
https://github.com/nearprotocol/near-shell/pull/328#issuecomment-619889936

**Comment by frol** [comment]
This issue has been mostly fulfilled. Reimplementing the validator schedule in JS is quite an effort, so I suggest we close this issue and either open a new one for the remaining item or only get back to it once we have a real need for that (it is advanced tooling for the validators, but currently we have a stable set of validators, so I don't think it is that important now).
