### ISSUE TITLE
Expose state stake and account balance breakdown

### ISSUE THREAD

**Issue by kcole16** [near/near-api-js#298]
### Overview
We currently do not expose an account's complete balance breakdown, specifically the "state stake". This is necessary to compute the account's spendable balance. 

Both the [Wallet](https://github.com/nearprotocol/near-wallet/issues/481) and Explorer need to retrieve and display the state stake amount, and it's likely app devs will want the same data (so they can determine if users have a sufficient NEAR balance for a TX).

`account/<account_id>` RPC example
```bash
{
  "result": {
    "amount": "10000000999999952626000000",
    "locked": "0",
    "storage_usage": 387
  }
}
```

The spendable balance = `amount` - `state_stake`

The state stake can be calculated from `storage_usage * storage_amount_per_byte`.  

`cost_per_byte` can be retrieved from [RPC method = EXPERIMENTAL_genesis_config](https://docs.nearprotocol.com/docs/api/rpc-experimental#genesis-config) which exposes `runtime_config.storage_amount_per_byte`

cc @Patrick1904 @vgrichina

**Comment by kcole16** [comment]
One way to do this is to add a [getAccountBalance](https://github.com/nearprotocol/near-wallet/blob/c7e2dedc54026f175198e9d8c1852b158604eb98/src/utils/wallet.js#L288) function to the `Account` object: https://github.com/near/near-api-js/blob/master/src/account.ts

> I'd also change it to just return object with all different "types" of balance instead of taking `type` argument.

_Originally posted by @vgrichina in https://github.com/nearprotocol/near-wallet/pull/534#issuecomment-620295470_

**Comment by vgrichina** [comment]
Note that there is generally no changes needed in near-api-js to get info from experimental endpoints.

`sendJsonRpc` can be used directly for such situations:
https://github.com/near/near-api-js/blob/db51150b98f3e55c2893a410ad8e2379c10d8b73/src/providers/json-rpc-provider.ts#L114

**Comment by bowenwang1996** [comment]
@kcole16 for regular users state stake is usually quite small (something like 0.01), do you think it is still good to display that?

**Comment by kcole16** [comment]
@bowenwang1996 We're planning to display as "minimum balance". The total balance will be displayed in most places by default, and spendable will be highlighted on TX and "Send Money" pages.

https://github.com/near/near-wallet/issues/481
