### ISSUE TITLE
difference between WalletConnection and Account is confusing

### ISSUE THREAD

**Issue by amgando** [near/near-api-js#324]
it's confusing when opening a connection to NEAR with change methods (which will require signing) to be able to do this with an Account that does not have the ability to sign transactions which include a transfer of funds.

**Account**
https://github.com/near/near-api-js/blob/master/src/account.ts#L115-L157

**WalletConnection**
https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L179-L217

the current behavior is that the transaction fails with a server timeout and no other useful information to help troubleshoot the problem

better behavior would be to clarify that a `functionCall` transaction with non zero `amount` attached must use a `WalletConnection` account so that it includes the wallet redirect to authorize the transfer

see current behavior
https://www.loom.com/share/f20a2ee04b3c4e65a90167d16ce1fd4d

**Comment by volovyk-s** [comment]
Looks like we already have this in docs: https://docs.near.org/docs/tutorials/front-end/naj-examples#the-wallet-interface
