### ISSUE TITLE
provide a better wallet_auth_key prefix

### ISSUE THREAD

**Issue by amgando** [near/near-api-js#325]
currently wallet uses a user-defined prefix for the key in LocalStorage

note:

***undefined_*** wallet_auth_key

```
 {
 "undefined_wallet_auth_key": 

 {"accountId":"sherif-demo.testnet","allKeys":["ed25519:Azqg7VBLGYo8LdiJ4SEzgodg3JXANoJm8jbH1homoVj6"]} 

}
 ```

this could be improved with a more friendly default value for `appKeyPrefix `

[https://github.com/near/near-api-js/blob/25e7e60203965aee062ca19f352ff765859896ef/src/wallet-account.ts#L28](https://github.com/near/near-api-js/blob/25e7e60203965aee062ca19f352ff765859896ef/src/wallet-account.ts#L28)

**Comment by mikedotexe** [comment]
@stefanopepe does this sound like a change that will break Wallet or have concerns with this?

**Comment by stefanopepe** [comment]
> @stefanopepe does this sound like a change that will break Wallet or have concerns with this?

We are re-designing the key management, and we'll start working on it in the next sprint. The UX will probably include a way for the user to append notes/memorable information to each key, but I don't have more information to share right now.

Roping in @MaximusHaximus for an estimation of the changes

**Comment by MaximusHaximus** [comment]
I did an audit, and I don't believe that we reference this `_wallet_auth_key` localstorage value anywhere in the wallet codebase directly.  As a result, as long as long as `near-api-js` handles backwards compatibility internally for anything that relies on it in `near-api-js`, it shouldn't have any impact on the wallet as far as I can tell. :)
