### ISSUE TITLE
findSeatPrice not accessible

### ISSUE THREAD

**Issue by htafolla** [near/near-api-js#333]
I am unable to getSeatPrice from the API. I have tried many options and tried to recompile the code with different import/export permutations. 

There is an existing reference to validators in the compiled js that references a function. I believe they get removed. See https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

    ERROR:
    Uncaught (in promise) TypeError: Cannot read property 'findSeatPrice' of undefined

BASIC SETUP Index.js

```js
const { validators } = require('near-api-js');

async function validatorsInfo(near, epochId) {

    const genesisConfig = await near.connection.provider.sendJsonRpc('EXPERIMENTAL_genesis_config', {});
    const result = await near.connection.provider.sendJsonRpc('validators', [epochId]);
    result.genesisConfig = genesisConfig;
    result.numSeats = genesisConfig.num_block_producer_seats + genesisConfig.avg_hidden_validator_seats_per_shard.reduce((a, b) => a + b);
    return result;
}

async function initContract() {
    const result = await validatorsInfo(near, null);
    const seatPrice = validators.findSeatPrice(result.current_validators, result.numSeats);
   ...
}
```

**Comment by potatodepaulo** [comment]
@htafolla thanks! This is a very clean bug report.

Acceptance criteria:
* `findSeatPrice` is accessible or research how the method behavior should work.
* The above use case works or an alternative is provided.

**Comment by janedegtiareva** [comment]
Thank you for reporting an issue! I was able to reproduce the behavior. It looks like the problem is in the validatorsInfo code function (it does not return). Could you please try to change it to the following and see if this works for you:

`
async function validatorsInfo(near, epochId) {

    const genesisConfig = await near.connection.provider.sendJsonRpc('EXPERIMENTAL_genesis_config', {});
    const result = await near.connection.provider.sendJsonRpc('validators', [epochId]);
    result.genesisConfig = genesisConfig;
    result.numSeats = genesisConfig.num_block_producer_seats + genesisConfig.avg_hidden_validator_seats_per_shard.reduce((a, b) => a + b);
    return result;
}`

**Comment by htafolla** [comment]
@janedegtiareva whoops you caught a typo in my submission there. Unfortunately, the issue is with the call to "validators.findSeatPrice" though. Does it work for you?

**Comment by vgrichina** [comment]
@htafolla I cannot reproduce this error. Steps I tried:
1. Go to empty directory.
2. `yarn add near-api-js`
3. Try using it in `node` REPL:
```
[I] ➜ node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> const { validators } = require('near-api-js');
undefined
> validators.findSeatPrice()
Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.findSeatPrice (/Users/vg/Documents/tmp-near/node_modules/near-api-js/lib/validators.js:14:31)
> 
```

So while there is error downstream looks like the method itself is found.

I think one of following might be happening:
1) you have different version of `near-api-js` installed. Try installing latest one? I did test with `0.25.1`
2) some other `validators` usage in the code (missing from snippet) is overriding somehow

**Comment by htafolla** [comment]
@vgrichina it works correctly from Node REPL. However, if you clone: https://github.com/near/create-near-app and update the index.js it does not work:

`async function initContract() {

    const { validators } = require('near-api-js');
    console.log(validators);
    console.log(validators.findSeatPrice());
    ...
`
Chrome console response:
`
undefined
TypeError: Cannot read property 'findSeatPrice' of undefined
    at _callee$ (index.js:39)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (index.js:5)
    at _next (index.js:5)
`

**Comment by vgrichina** [comment]
@htafolla got it, we probably missed it from browser entry point. I think you might workaround by importing specific module, smth like:

`const validators = require('near-api-js/lib/validators')`

**Comment by htafolla** [comment]
@vgrichina Thanks! I can confirm this works:
`const validators = require('near-api-js/lib/validators')`

I have noticed this with other classes/types as well. Is the recommended approach to import from the `lib` directory?

**Comment by chadoh** [comment]
We have a separate `browser-index.js` file that is used as the entry point for browsers, while `index.js` is used as the entry point for nodejs. It looks like the two have become out-of-sync; `browser-index.js` does not import & re-export `validators` the way that `index.js` does. My guess is that the other classes/types you noticed probably stem from the same issue.

I will extract the common exports to a `common-index.js` to make sure this doesn’t happen going forward, and so that you can stop using the `near-api-js/lib/...` workaround.

**Comment by vgrichina** [comment]
this is fixed here AFAIK https://github.com/near/near-api-js/releases/tag/v0.26.0

@chadoh sorry didn't see your comment here and just decided to fix as needed to cut release with other stuff (like new RPCs)
