### ISSUE TITLE
Missing Signature Verification Method

### ISSUE THREAD

**Issue by damons** [near/near-api-js#339]
Do we need a method to verify signatures?  We can sign, but how does one verify?

**Comment by abacabadabacaba** [comment]
Given nearprotocol/nearcore#2833, we probably need to rethink our cryptographic API.

**Comment by schadokar** [comment]
Is there any method available to verify the signature using Public Key? Verify method is only available for KeyPair which requires Secret Key.  @abacabadabacaba

**Comment by raymondfeng** [comment]
+1 to have a standalone `verify`. Here is my implementation:

```ts
export function verifySignature(
  message: Uint8Array | string,
  signature: Uint8Array | string,
  publicKey: string | PublicKey,
): boolean {
  const pk = PublicKey.from(publicKey).data;
  if (typeof message === 'string') {
    message = Buffer.from(message, 'utf-8');
  }
  if (typeof signature === 'string') {
    signature = Buffer.from(signature, 'hex');
  }
  return nacl.sign.detached.verify(message, signature, pk);
}
```

**Comment by Sotatek-TungLe3** [comment]
> +1 to have a standalone `verify`. Here is my implementation:
> 
> ```ts
> export function verifySignature(
>   message: Uint8Array | string,
>   signature: Uint8Array | string,
>   publicKey: string | PublicKey,
> ): boolean {
>   const pk = PublicKey.from(publicKey).data;
>   if (typeof message === 'string') {
>     message = Buffer.from(message, 'utf-8');
>   }
>   if (typeof signature === 'string') {
>     signature = Buffer.from(signature, 'hex');
>   }
>   return nacl.sign.detached.verify(message, signature, pk);
> }
> ```

Hi are you verifying onchain or offchain? If it's onchain, how can I verify using rust?

**Comment by frol** [comment]
@Sotatek-TungLe3 Here is a contract that does signature verification in Rust on chain: https://github.com/frol/near-birthday-quest/blob/f23dc85da51b44ecdc437d945f3adeababf98cd1/contract/src/lib.rs#L17-L41

**Comment by Sotatek-TungLe3** [comment]
What "H5ANpdUoXVwhYBgAgEi1ieMQZKJbwxjPJtHX4vkVcSnF" is? If it is private key and reveal on smart contract, anyone can use the key to sign their message and take a present right?

**Comment by frol** [comment]
@Sotatek-TungLe3  please, read the code carefully, that is public key

**Comment by Sotatek-TungLe3** [comment]
My bad. Thanks for your answers

**Comment by Sotatek-TungLe3** [comment]
@frol Thanks for your answer but what if user finds last tx inputs and reuses them to create a new tx? They can take present right? How can we prevent it?

**Comment by Sotatek-TungLe3** [comment]
Do you have any way to prevent replay attack in this case?

**Comment by Sotatek-TungLe3** [comment]
Can you help me solve this issue? https://stackoverflow.com/questions/74517462/how-to-create-signature-as-an-input-for-type-vecu8-on-smart-contract
Tks
