### ISSUE TITLE
Gate tests (and eventually code) by target nearcore version range

### ISSUE THREAD

**Issue by vgrichina** [near/near-api-js#34]

**Comment by chadoh** [comment]
@vgrichina has this been addressed?

**Comment by vgrichina** [comment]
@chadoh some of the tests do it https://github.com/near/near-api-js/blob/0e9e2c76d39ac1a3be4159a3e16a3bbc96857cf5/test/account.test.js#L71

Make sense to extract it into some utility module though to make it easy to use in any test.

**Comment by vikinatora** [comment]
Hi @vgrichina, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this issue seems no longer relevant. Please let me know if that's not the case; otherwise, I'll proceed to close the issue in 5 days.

**Comment by vikinatora** [comment]
Closing as issue isn't relevant anymore.
