### ISSUE TITLE
Utility to verify account when accessing off-chain storage 

### ISSUE THREAD

**Issue by vgrichina** [near/near-api-js#342]
As a developer of complex web app (e.g. NEAR Wallet) I want to store some user data off chain for privacy/performance reasons. As a part of this I need to make sure that user accessing data has keys necessary for NEAR account access.

There is example of this in existing projects:

*   sign current block index [https://github.com/near/near-wallet/blob/0e141ef6c9c42315cf0aa30853c42218558ef44e/src/utils/wallet.js#L305](https://github.com/near/near-wallet/blob/0e141ef6c9c42315cf0aa30853c42218558ef44e/src/utils/wallet.js#L305)
*   verify signature [https://github.com/near/near-contract-helper/blob/cf9bab1f05d3e639bb01c104cb465b35c89992b8/app.js#L133](https://github.com/near/near-contract-helper/blob/cf9bab1f05d3e639bb01c104cb465b35c89992b8/app.js#L133)

Looks like it's useful for other projects as well, so we should extract it into `near-api-js`.

**Comment by hdriqi** [comment]
Here's my current implementation

On the client-side, you can create a b64 encoded token that contain `userId`, `pubKey` and `signature`. You can put this token on authorization header which will be sent to backend.
```
async authToken() {
    const userId = near.currentUser.accountId
    const arr = new Array(userId)
    for (var i = 0; i < userId.length; i++) {
      arr[i] = userId.charCodeAt(i)
    }
    const msgBuf = new Uint8Array(arr)
    const signedMsg = await this.signer.signMessage(msgBuf, this.wallet._authData.accountId, this.wallet._networkId)
    const pubKey = Buffer.from(signedMsg.publicKey.data).toString('hex')
    const signature = Buffer.from(signedMsg.signature).toString('hex')
    const payload = [userId, pubKey, signature]
    return Base64.encode(payload.join('&'))
  }
```

On backend side, you need to:
1. Verify the signature that contain userId using the pubKey
2. Match the userId and pubKey onchain

This code is used as middleware for expressjs
```
const authHeader = req.headers.authorization
const decodeAuthHeader = Base64.decode(authHeader)
const [userId, pubKey, signature] = decodeAuthHeader.split('&')
const pubKeyArr = _hexToArr(pubKey)
const signatureArr = _hexToArr(signature)
const hash = new Uint8Array(sha256.sha256.array(userId))
const verify = nacl.sign.detached.verify(hash, signatureArr, pubKeyArr)
if (!verify) {
  return res.status(400).json({
    success: 0,
    message: 'unauthorized'
  })
}
const b58pubKey = bs58.encode(Buffer.from(pubKey.toUpperCase(), 'hex'))
const response = await axios.post(`https://rpc.testnet.near.org`, {
  jsonrpc: '2.0',
  id: 'dontcare',
  method: 'query',
  params: {
    request_type: 'view_access_key',
    finality: 'final',
    account_id: userId,
    public_key: `ed25519:${b58pubKey}`
  }
})

if (response.data.result && response.data.result.error) {
  return res.status(401).json({
    success: 0,
    message: 'unauthorized'
  })
}
req.userId = userId
next()
```

**Comment by potatodepaulo** [comment]
Thanks @hdriqi this is helpful. What are you using this for right now?

**Comment by hdriqi** [comment]
@potatodepaulo I'm using it to verify users when they send data to offchain storage, my use case is to store the user follow/unfollow data which then will be used to sort/filter their news feeds which isn't practical if it is being programmed on chain (imagine filtering million posts for user with thousands following)
