### ISSUE TITLE
Change how transaction status polling is done

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-api-js#344]
Currently we send transactions in near-api-js using `broadcast_tx_commit` and it caused issues like https://github.com/near/near-api-js/issues/127 because nearcore will return an unstructured error for timeout and it makes it difficult to handle on the client side. However, not only does the error on nearcore side take longer time to fix, `broadcast_tx_commit` is also not really the best way to submit transactions. I suggest that we use a combination of `EXPERIMENTAL_broadcast_tx_sync` and `EXPERIMENTAL_check_tx` to handle transaction submission and status checking on near-api-js side. This completely eliminates the possibility of timeout error from nearcore side and allows more flexibility for polling transaction status as there is no internal polling in nearcore in either `EXPERIMENTAL_broadcast_tx_sync` or `EXPERIMENTAL_check_tx`.

Some caveats:
* Errors need to be handled properly. When `EXPERIMENTAL_check_tx` returns `InvalidNonce` for example, it actually means that the transaction likely has already succeeded and therefore the nonce on the access key has increased, making the original transaction invalid.
* When `EXPERIMENTAL_check_tx` returns `None`, it means that the transaction is still valid, but this might imply that something went wrong in between (get stuck in mempool for example). So near-api-js should have some timeout on its own to decide that the transaction is not accepted and a new one should be sent.

@vgrichina @kcole16 What do you think?

**Comment by vgrichina** [comment]
@bowenwang1996 how do we distinguish:
- this transaction is invalid because other transaction got submitted with given nonce (or larger)
- this transaction actually got submitted successfully. Does check_tx provide such distinction?

Also note that without any way to get push with update on status of transaction this method of submitting transactions going to be inherently higher latency than properly done server-side implementation would be. So it’s only acceptable as a workaround while nearcore needs to come up with some solution that can be permanent.

**Comment by potatodepaulo** [comment]
Reason it's labelled bug: The timeout error sucks and is confusing to people.

**Comment by bowenwang1996** [comment]
@vgrichina you have to poll the transaction status to be able to distinguish the two. I think it should work fine if the network is running normally, but you are right in that if the network is slow it can be quite suboptimal. But again, I don't think having internal polling helps a lot in this case.

**Comment by vgrichina** [comment]
> I think it should work fine if the network is running normally

Making one extra request is never good. Neither for client on slow connection (easily few extra seconds per extra request), nor for nearcore. 

If I'm already checking on a given TX, why not return full status? It looks like now I need to call both `tx-status` and `check_tx` continuously in a loop while waiting for transaction to land.

**Comment by bowenwang1996** [comment]
Good point. I think we can make `check_tx` fetch transaction status as well. cc @frol

**Comment by ilblackdragon** [comment]
@frol Should we merge back `check_tx` login into `tx-status` - `tx-status` should just support either hash or full transaction bytes and return status or invalid?

@vgrichina you mentioned that every other service returns result. Are you saying that services don't have timeouts? If the question that our timeouts are too short for most cases in `_commit` operation - we can extend it. E.g. we have legit timeouts right now when some nodes are not operating.

@frol @bowenwang1996 in our `_commit` operations while we polling, we should also check if transaction is still valid within the polling loop. 

E.g. [`tx_status_fetch`](https://github.com/nearprotocol/nearcore/blob/4bbf187f38966bcfc53213a52f848d4e71884f77/chain/jsonrpc/src/lib.rs#L250) can stake either hash or transaction itself. And ping TxStatus ViewClient with that. And it can then return if transaction becomes invalid during polling.

**Comment by vgrichina** [comment]
@ilblackdragon original issue was that we not just timed out early, but also timed out in case of error. So both cases were indistinguishable. Ideal API based on long-polling would be:
- you send tx, it either times out or returns result/error when it becomes available
- if it times out – we can call the same RPC again with same transaction and it also either times out or returns result/error when done
- this is done in the loop until client-side timeout happens 

Alternatively without long-polling but with web sockets:
- send tx asynchronously, subscribe for updates for given tx hash
- get all status updates on tx pushed via web socket subscription

**Comment by ilblackdragon** [comment]
I agree with @vgrichina and it can be solved actually pretty easily. Filed an issue here: https://github.com/nearprotocol/nearcore/issues/2867

near-api-js should just switch to retry `broadcast_tx_commit` if it timed out.

**Comment by vgrichina** [comment]
> if it times out – we can call the same RPC again with same transaction and it also either times out or returns result/error when done

just to be clear – this should be idempotent. If transaction has already succeeded before – I expect to get success submitting it again.

**Comment by bowenwang1996** [comment]
> If transaction has already succeeded before – I expect to get success submitting it again.

That makes sense. We can check transaction status first.

**Comment by janedegtiareva** [comment]
@vgrichina are you working on this?

**Comment by vgrichina** [comment]
@janedegtiareva I've made workaround https://github.com/near/near-api-js/pull/350

AFAIK @bowenwang1996 also submitted better fix on nearcore side:
https://github.com/nearprotocol/nearcore/pull/2883

I'm not sure whether it's propagated to testnet/mainnet already.

@bowenwang1996 where is this released already?

**Comment by bowenwang1996** [comment]
@vgrichina it is available on betanet and will be released to testnet next Monday. Given that it is already Thursday I won't think  it makes sense for me to patch testnet with this commit right now.

**Comment by janedegtiareva** [comment]
Can this issue be closed now @bowenwang1996, or do you have more suggestions?

**Comment by bowenwang1996** [comment]
It appears that something doesn't work very well. I have seen people reporting nonce issues and other issues with retry. We should probably look into it.

**Comment by frol** [comment]
> It appears that something doesn't work very well. I have seen people reporting nonce issues and other issues with retry. We should probably look into it.

Seems to be resolved in https://github.com/nearprotocol/nearcore/pull/3061
