### ISSUE TITLE
When near-api-js updates TypeScript dependency, my project breaks

### ISSUE THREAD

**Issue by chadoh** [near/near-api-js#368]
***Describe the bug***
 Recently (maybe [https://github.com/near/near-api-js/commit/a3e587b74?](https://github.com/near/near-api-js/commit/a3e587b74?)), NAJ updated its TypeScript dependency. This caused the `lib/index.d.ts` file to use syntax that was only supported by TS version greater than 3.8:

```
 Syntax not supported by TS version < 3.8
 export * as aliasName from './path/to/the/file'
 ```

It took partners using an older version of TS a long time to track down and fix the issue.

NAJ should play more nicely with everyone relying on an older TS version, and give expectable deprecation warnings when support for a newer TS version is added.

***Additional context***
 It looks like <span class="error">[this is a known frustration with TypeScript]</span>([https://github.com/microsoft/TypeScript/issues/31907](https://github.com/microsoft/TypeScript/issues/31907)) that should ideally be fixed by the TypeScript team. However, the TS team did provide a rudimentary means for library authors to control this in September 2018: [https://github.com/microsoft/TypeScript/pull/26568](https://github.com/microsoft/TypeScript/pull/26568)

**Comment by vikinatora** [comment]
Closing as it's not relevant anymore.
