### ISSUE TITLE
Error from transaction printed doesn't have any detail

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#401]
***Describe the bug***
 Currently `printLogsAndFailures` doesn't show any detail about error.
 Usually it's something like `Error: 

 {"index":0} 

`

***Expected behavior***
 TransactionResult contains status.Failure with detail information.
 Currently the way the information gets extracted is broken.

**Comment by vgrichina** [comment]
@ilblackdragon going to address as part of https://github.com/near/near-api-js/issues/331
