### ISSUE TITLE
near-api-js tests fail on nearcore

### ISSUE THREAD

**Issue by frol** [near/near-api-js#410]
**Describe the bug**

Every new PR to nearcore (e.g. https://github.com/nearprotocol/nearcore/pull/3372) fails on near-api-js tests: https://buildkite.com/nearprotocol/nearcore/builds/3746#98d958cf-cfd9-482c-9987-8b0f86873142

**To Reproduce**

Run "nearlib test" on nearcore CI.

**Expected behavior**

Tests used to pass.

**Screenshots**

![image](https://user-images.githubusercontent.com/304265/94250626-d7419c80-fef7-11ea-8010-991d6c896764.png)

**Comment by chefsale** [comment]
Created a PR for the fix: https://github.com/near/near-api-js/pull/411, seems to be an issue in different NODE_ENVs. We use in nearcore local and travis is using ci and ci-betanet.
