### ISSUE TITLE
Account.signAndSendTransaction" console usage should be controllable by the caller

### ISSUE THREAD

**Issue by miohtama** [near/near-api-js#420]
***Describe the bug***

Currently there is implicit usage of `console.warn` in `Account.signAndSendTransaction`.

This causes messed up output e.g. when running tests that use `near-api-js` and test for failing transactions.

***To Reproduce***

A sample from the log output that tests for a failed contract call:

```
 PASS src/pool.test.js (27.695 s)
 ✓ Deploy pool contract (7049 ms)
 ✓ Cannot initialize pool twice (10436 ms)

 console.log
 Receipt: 72kUkJ4jZxTHQ5iH2nKGZ9ekfhSUW4qr7q6aTroYrAyM

 at Account.printLogsAndFailures (node_modules/near-api-js/lib/account.js:59:21)

 console.warn
 Failure <span class="error">[cnt-1601418033722-314800]</span>: Error: Smart contract panicked: panicked at 'Already initialized', pool/src/lib.rs:60:9

 at Account.printLogsAndFailures (node_modules/near-api-js/lib/account.js:62:25)
 at Account.signAndSendTransaction (node_modules/near-api-js/lib/account.js:132:14)
 at node_modules/near-api-js/lib/contract.js:47:39

Test Suites: 1 passed, 1 total
 Tests: 2 passed, 2 total
 Snapshots: 0 total
 Time: 27.826 s
 Ran all test suites.
 ```

***Suggested solution***

Having console statements in the codebase is considered a bad habit and may cause issues like described above.

Any `console` usage should be caller controllable e.g. as a function argument and/or globally in connection object. Preferably, the caller can pass their own console object to be used for logging, or null if no implicit output is desired.

**Comment by vikinatora** [comment]
Should be resolved with #1215
