### ISSUE TITLE
testnet account creation autofunds x.testnet accounts

### ISSUE THREAD

**Issue by dtp263** [near/near-api-js#438]
**Describe the bug**
When trying to create an account programmatically via the near-api-js I am able to create `x.testnet` accounts without transferring any tokens to them. It seems an autofaucet is taking action even when it is not specified.

**To Reproduce**
1. Connect to near without specifying any keys. (anonymous connection)
2. Use the near method `createAccount` found [here](https://github.com/near/near-api-js/blob/93e8a6025cb278cbdfaf97983aea514ccfa1a016/src/near.ts#L63)
3. Watch account get created with 500N

**Expected behavior**
This should fail and not be auto-funded as it does on mainnet. It seems for some reason on testnet the permissions are not set correctly regarding this method because as an anonymous user i should not be able to create `X.testnet` accounts.

**Comment by mehtaphysical** [comment]
@dtp263 This only happens if you pass the `helperUrl` config option when connecting to NEAR: https://near.github.io/near-api-js/interfaces/connect.connectconfig.html#helperurl.
