### ISSUE TITLE
RPC error parsing is wrong

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#441]
**Describe the bug**
Most of the action errors from RPC are right now not shown and developer just sees "Error: {}"

**To Reproduce**
1. Send a transaction with 0 gas
2. See that error is "Error: {}"

**Expected behavior**
Shows error with not enough gas

**Screenshots**
<img width="460" alt="Screen Shot 2020-10-22 at 11 12 37 AM" src="https://user-images.githubusercontent.com/175486/96924023-eb30dd80-1466-11eb-9aa6-77eb5c3a308c.png">

**Comment by ilblackdragon** [comment]
To be clear, RPC returns correct errors and it's the parsing in the near-api-js that doesn't capture the error

**Comment by volovyk-s** [comment]
Already fixed
