### ISSUE TITLE
Extract creating single-key signer as common utility

### ISSUE THREAD

**Issue by vgrichina** [near/near-api-js#450]
seems like this pattern is repeating enough times that makes sense to extract as utility. `InMemorySigner.fromKeyPair` maybe?

_Originally posted by @vgrichina in [https://github.com/near/near-api-js/pull/445#r520200050_](https://github.com/near/near-api-js/pull/445#r520200050_)

**Comment by vgrichina** [comment]
@mattlockyer as I understand this is done on near-api-js side already, but we still need to convert some of the wallet code, etc. Correct?

**Comment by mattlockyer** [comment]
Yes, it's been working in a test for account_multisig, we can start using it in wallet.

Should we add explicit regression test for this?

**Comment by vgrichina** [comment]
@mattlockyer yeah, makes sense to do a test that it can sign.
