### ISSUE TITLE
getAccountBalance() - Stake amount doesn't work for delegated amounts

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/near-api-js#459]
***Describe the bug***
 I believe there is a missing case where the "locked" balance of an account does not take into account staked amounts in pool contracts.

***To Reproduce***
 1\. Using an account that delegated to a NEAR pool validator
 2\. use `getAccountBalance()` method
 3\. See "locked" amount

***Expected behavior***
 I want to be able to get a staked balance for all types of accounts. Either this method should explain that it only supports root staking![](/images/icons/emoticons/help_16.png) or provide another method for getting contract staked balances.

***Additional context***
 [https://github.com/near/near-api-js/blob/master/src/account.ts#L454](https://github.com/near/near-api-js/blob/master/src/account.ts#L454)

I also believe this is why the explorer reports 0 Ⓝ for account page as well:
 <img width="261" alt="Screen Shot 2020-11-23 at 10 43 58 PM" src="https://user-images.githubusercontent.com/2633184/100058044-75a98b80-2ddd-11eb-940b-43286fe653f8.png">

Further example showing need: 
 [https://github.com/near/account-lookup/blob/master/script.js#L138-L142](https://github.com/near/account-lookup/blob/master/script.js#L138-L142)

**Comment by mehtaphysical** [comment]
We should add ability to see delegated staking amount from `near-api-js` or provide some guide to show how to get this value using `near-api-js`.
