### ISSUE TITLE
RequestSignIn doesn't have a way to specify set of method names to restrict access

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#472]
`requestSignIn` method should take set of method names to restrict access to the specified contract name.

**Comment by mehtaphysical** [comment]
Need to update the wallet a bit for this I believe: https://github.com/near/near-wallet/blob/df50026299e4135b78c7a4af7235959f39df9dae/src/actions/account.js#L156.

Maybe pass the method names in the url like `?....&methodNames[]=addMessage&methodNames[]=deleteMessage`?

If this sounds good I'm happy to work on this.
