### ISSUE TITLE
Reference Documentation

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#483]
The current documentation is https://docs.near.org/docs/api/near-api-js which links to https://near.github.io/near-api-js/, which has very little information.

Compare this to https://docs.ethers.io/v5/ documentation with Getting Started, Cookbook, Testing examples, Contribution to this project, etc.

docs.near.org can pull the reference documentation from this near-api-js.

- [x] Reference docs (cheat sheet of API)
- [x] Cookbook
- [x] Type docs (updates and comments the auto-generated, in-line docs)
- [ ] FAQs/common pitfalls and gotchas

**Comment by volovyk-s** [comment]
Issue description is not relevant anymore, but the problem remains.
Current `near-api-js` docs: https://docs.near.org/docs/develop/front-end/near-api-js
@chadoh @kcole16 @thisisjoshford let's create some plan for `near-api-js` documentation enhancement.

**Comment by kcole16** [comment]
@thisisjoshford Highest priority workflows to demonstrate:
- Connect to a contract instance
- Call view methods on the contract
- Login (`requestSignIn`)
- Call change methods on the contract and redirect to Wallet to sign

**Comment by thisisjoshford** [comment]
> @thisisjoshford Highest priority workflows to demonstrate:
> 
> * Connect to a contract instance
> * Call view methods on the contract
> * Login (`requestSignIn`)
> * Call change methods on the contract and redirect to Wallet to sign

absolutely agree

**Comment by mikedotexe** [comment]
Bumping this, would yall like to sync on this and brainstorm for the last two checkboxes, cookbook and common pitfalls?

**Comment by mikedotexe** [comment]
Pitfall suggestion: when you're updating your smart contract and your frontend doesn't see the new method. Didja remember to update this part?

<img width="1108" alt="Screen Shot 2021-05-06 at 12 52 34 PM" src="https://user-images.githubusercontent.com/1042667/117357797-3aba8200-ae6a-11eb-8838-1ad45e877f41.png">

**Comment by mikedotexe** [comment]
Cookbook idea: I'm a user who feels like I might have had my Windows machine compromised by the Solar Winds hack. I no longer trust the keys stored on my computer. I'd like to "rotate keys" meaning adding new keys and removing old ones.

**Comment by mikedotexe** [comment]
Pitfall suggestion: Wait, how do I attach a custom gas amount or NEAR to a function call again?

I saw this in `create-near-app`

```js
    await window.contract.set_greeting({
      // pass the value that the user entered in the greeting field
      message: greeting.value
    })
```

but I don't know what to change?

Answer: calm down, bro, and take a look at guest book:

```js
contract.addMessage(
  { text: message.value },
  BOATLOAD_OF_GAS,
  Big(donation.value || '0').times(10 ** 24).toFixed()
).then(() => {
  contract.getMessages().then(messages => {
    setMessages(messages)

    message.value = ''
    donation.value = SUGGESTED_DONATION
    fieldset.disabled = false
    message.focus()
  })
})
```

but in actuality, give an easier example cuz the above code could be simpler.

**Comment by mikedotexe** [comment]
Pitfall suggestion: Ack! I'm trying to do some basic NodeJS script and it's complaining about something something "window" what am I doing wrong?

It sounds like maybe you're using a KeyStore that's for the browser. Here is an example of using a keystore for the browser.

// your example here

and here is an example of a file system keystore, which is probably what you're wanting to do:

// other example here

**Comment by mikedotexe** [comment]
Cookbook idea: I want to execute a transaction that may or may not do cross-contract calls, then I wanna see how much gas was burned. I think I'll need to do a transaction, get the resulting tx hash, get info on that, then add up `gas_burnt`.

Is there a snippet for this?

Answer: yes there is, and our man Josh has done this when doing the killer storage doc, here's the snippet:

// code here

**Comment by mikedotexe** [comment]
Pitfalls suggestion: Uh oh! I keep seeing this weird console error in my app that I based off of other examples:

>regeneratorRuntime is not defined

<img width="525" alt="Screen Shot 2021-05-06 at 1 50 24 PM" src="https://user-images.githubusercontent.com/1042667/117363911-195d9400-ae72-11eb-8e54-4f37ada0c5d4.png">

What's going on?

Answer: ah yes, you are probably using Parcel like we do in other examples. Please make sure you have this line at the top of your main js file, likely `index.js`:

`import 'regenerator-runtime/runtime'`

and ensure the dependencies for this are also added to the project as dev dependencies by running… blah blah blah

**Comment by mikedotexe** [comment]
Pitfalls suggestion: Gah! I feel like I'm so close with these Jest tests, but I just don't know what's happening behind the scenes? Where are these magic objects being set up?

Answer: We feel your pain. Check out the `package.json` file of some of our examples, particularly near the bottom where there's this block:

```js
  "jest": {
    "testEnvironment": "near-cli/test_environment",
    "testPathIgnorePatterns": [
      "<rootDir>/contract/",
      "<rootDir>/node_modules/"
    ]
  }
```

This means we're using a custom environment, which may be something most web2 developers haven't had to do.
That's where you can see where the sausage is made.

Why did we do this in `near-cli`? I dunno! Please help contribute and fix this strangeness, friends.

**Comment by mikedotexe** [comment]
Cookbook suggestion: I heard there's a thing called "batch transactions" but I am not sure how to do it. Is there an example?

Well, you can check this out: https://github.com/near/core-contracts/tree/master/multisig#usage

This is what it would look like:

```js
const fs = require('fs');
const account = await near.account("illia");
const contractName = "multisig.illia";
const methodNames = ["add_request","delete_request","confirm"];
const newArgs = {"num_confirmations": 2};
const result = account.signAndSendTransaction(
    contractName,
    [
        nearAPI.transactions.createAccount(),
        nearAPI.transactions.transfer("100000000000000000000000000"),  
        nearAPI.transactions.addKey(
            nearAPI.utils.PublicKey.from("Eg2jtsiMrprn7zgKKUk79qM1hWhANsFyE6JSX4txLEuy"),
            nearAPI.transactions.functionCallAccessKey(contractName, methodNames, null)),
        nearAPI.transactions.addKey(
            nearAPI.utils.PublicKey.from("HghiythFFPjVXwc9BLNi8uqFmfQc1DWFrJQ4nE6ANo7R"),
            nearAPI.transactions.functionCallAccessKey(contractName, methodNames, null)),
        nearAPI.transactions.addKey(
            nearAPI.utils.PublicKey.from("2EfbwnQHPBWQKbNczLiVznFghh9qs716QT71zN6L1D95"),
            nearAPI.transactions.functionCallAccessKey(contractName, methodNames, null)),
        nearAPI.transactions.deployContract(fs.readFileSync("res/multisig.wasm")),
        nearAPI.transactions.functionCall("new", Buffer.from(JSON.stringify(newArgs)), 10000000000000, "0"),
    ]);

```

**Comment by mikedotexe** [comment]
Cookbook: Can I actually create a testnet/mainnet account programmatically without using Wallet.

Answer: Yup.

Something like:

```js
const { connect, keyStores, utils } = require('near-api-js');
const path = require('path');
const homedir = require('os').homedir();

const CREDENTIALS_DIR = '.near-credentials';

const nearConfig = {
  networkId: 'mainnet',
  nodeUrl: 'https://rpc.mainnet.near.org',
  walletUrl: 'https://wallet.mainnet.near.org',
  helperUrl: 'https://helper.mainnet.near.org'
};

if (process.argv.length === 2) {
  console.info('Please enter in the form\nnode create-mainnet-account EXISTING_ACCOUNT.near NEW_ACCOUNT.near ED25519_PUBLIC_KEY\nIt will create an account with 3 Ⓝ if it\'s available');
  return;
}

AccountGoBrrr = {
  begin: async function() {
    const credentialsPath = path.join(homedir, CREDENTIALS_DIR);
    const keyStore = new keyStores.UnencryptedFileSystemKeyStore(credentialsPath);
    const near = await connect(Object.assign({ deps: { keyStore } }, nearConfig));
    const creatorAccount = await near.account(process.argv[2]);

    return await creatorAccount.functionCall(
      'near',
      'create_account',
      {
        new_account_id: process.argv[3],
        new_public_key: process.argv[4]
      },
      '300000000000000',
      utils.format.parseNearAmount(process.argv[5])
    )
  }
};

AccountGoBrrr.begin();
```

**Comment by mikedotexe** [comment]
Cookbook suggestion: I don't need a full-blown indexer, but would like to go backwards some limited about of blocks and see details on recent transactions. How can I go backwards using this library?

Answer: check out the Chainlink Demo: https://github.com/near-examples/chainlink-demo

```js
export async function getBlockByID(blockID){
    const near = await getNear();
    const blockInfoByHeight = await near
      .connection.provider.block({
        blockId: blockID,
    })
  return blockInfoByHeight
}

function blah {
  // might use something like this, taken from 
    // get the most current block hash and corresponding block
    const latestHash = (await this.props.provider.status()).sync_info.latest_block_hash;
    const latestBlock = await this.props.provider.block(latestHash);

  // the below is from Chainlink Demo

  // creates an array of block IDs based on first and last block
  const blockArr = [];
  let blockHash = lastBlock;
  let currentBlock;
  do {
    currentBlock = await getBlockByID(blockHash);
    blockArr.push(currentBlock.header.hash);
    blockHash = currentBlock.header.prev_hash;
  } while (blockHash !== firstBlock)
}

kDetails = await Promise.all(
    blockArr.map(block => {
      return getBlockByID(block);
    }))

  // returns an array of chunk hashes from block details
  const chunkHashArr = [];
  blockDetails.map(block => {
    block.chunks.map(chunk => {
      chunkHashArr.push(chunk.chunk_hash);
    });
  });

  // returns chunk details based from the array of hashes
  const chunkDetails = await Promise.all(
    chunkHashArr.map(chunk => {
      return near.connection.provider.chunk(chunk);
  }));

  // checks chunk details for transactions
  // if there are transactions in the chunk
  // find ones associated with our two accounts
  const transactions = []
  chunkDetails.map(chunk => {
    chunk.transactions?.map(txs => {
      if (txs.signer_id.includes(`oracle-node.${nearAcct}`)) {
        transactions.push(txs);
      }
    });
  });

  // we want to exclude transactions from the oracle-node
  // so we return only transactions that contain these two methods
  const matchingTxs = transactions.reduce((acc, curr) => {
    curr.actions.map(action => {
      if (action.FunctionCall.method_name === "fulfill_request") {
        const args = action.FunctionCall.args;
        const base64DecodedArgs = Buffer.from(args, 'base64');
        const jsonArgs = JSON.parse(base64DecodedArgs.toString());
        if (jsonArgs.nonce === nonce) {
          acc.push(curr);
        }
      }
    }); return acc;
  }, [])
  // Note: at this point should be only one transaction

  //insert initial transaction into matchingTxs array
  matchingTxs.push(window.firstTransaction)

  //transaction receipts from other steps
  const txObj = await getTransaction(matchingTxs[0].hash, 'oracle-node');
  await getReceiptsFromAccountPrefix(txObj, 'client', 6)

  //creates transaction links from matchingTxs
  const txsLinks = matchingTxs.map(txs => (({
    method: txs.actions[0].FunctionCall.method_name,
    link: `https://explorer.testnet.near.org/transactions/${txs.hash}`
  })));
}
```

Probably simplify the above, but mainly keep all the logic about blocks, chunks, and transactions, and digging into them.

Some small snippet taken from my NEAR interview, which may be slightly outdated, but to get the lastest block and hash:
https://github.com/mikedotexe/near-interview/blob/master/src/App.js#L209-L211

**Comment by thisisjoshford** [comment]
Issue fixed with the following PRs:
- quick reference ->  https://github.com/near/docs/pull/647
- typeDocs -> https://github.com/near/near-api-js/pull/541
- cookbook -> https://github.com/near/docs/pull/693
- FAQs -> https://github.com/near/docs/pull/704
