### ISSUE TITLE
near-api-rust project

### ISSUE THREAD

**Issue by patrick-fitzgerald** [near/near-api-js#510]
Hi, 
I see there is a [near-api-js](https://github.com/near/near-api-js) and a [near-api-py](https://github.com/near/near-api-py) project. 
Is there any plans to create a near-api-rust library to interact with NEAR Protocol via RPC API?
I'm interested in using the RPC API with a rust client. 
If I was to create my own version. Is this the best source for the up to date [protos](https://github.com/near/NEPs/blob/67e0d46f1d72b631b39e57c3f55bb52bc9c0fb59/text/0000-transaction-refactoring.md#updated-protobufs) file?

Thanks,
Patrick

**Comment by bowenwang1996** [comment]
I think @frol had some ideas on this. Also we no longer use protobuf and currently use https://github.com/near/borsh instead.

**Comment by frol** [comment]
@patrick-fitzgerald it is JSON-RPC protocol, so there is no ProtoBuf involved. You can follow the [docs](https://docs.near.org/docs/develop/front-end/rpc) and implement a simple JSON-based client. We currently have [one for internal testing purposes](https://github.com/near/nearcore/tree/master/chain/jsonrpc/client), but it is not published on crates.io, and has quite a few dependencies that would be needed published before we can publish near-jsonrpc-client, also it lacks documentation.

**Comment by frol** [comment]
@patrick-fitzgerald if you are willing to contribute a re-write (or clean up the existing implementation) with proper documentation and sane usability, we can even create a bounty for that

**Comment by patrick-fitzgerald** [comment]
@frol Thanks I'll take a look at the internal project. A bounty for a rewrite sounds like a good idea. I could take a look at it some time in the future when I have more time.
