### ISSUE TITLE
Handle wrong nonce errors gracefully 

### ISSUE THREAD

**Issue by vgrichina** [near/near-api-js#52]
Should just retry with proper nonce when possible. Otherwise any concurrent request break apps.

**Comment by close-chat** [comment]
Yep, just ran into this. When spamming a certain transaction the nonce doesn't get incremented correctly clientside it seems :)

**Comment by volovyk-s** [comment]
@vgrichina is it the one that was solved with exponential backoff?

**Comment by vgrichina** [comment]
> @vgrichina is it the one that was solved with exponential backoff?

Yes
