### ISSUE TITLE
callbackUrl support is broken

### ISSUE THREAD

**Issue by myklemykle** [near/near-api-js#520]
**Is your feature request related to a problem? Please describe.**

I've been trying to work out how to use the Near Wallet's callbackUrl query arg, to pass my Near app's state across the wallet transaction without writing to the blockchain or local storage.  walletConnection.requestSignTransaction() has a callbackUrl argument specifically to support this.  But the only caller of that method is walletConnection.signAndSendTransaction(), which only allows the callbackUrl to be window.location.href, thereby blocking use of this feature.

**Describe the solution you'd like**

One solution would be for the autogenerated contract methods on the contract object to accept an optional extra options argument -- an object which could specify callbackUrl or other useful things in the future.

**Describe alternatives you've considered**

I can try to hack/patch this in myself and send a pull req, if this is a desired feature.  But if this is deprecated, if there's some other preferable approach to the problem of passing client state through a Near wallet transaction, please point me at it.  Thanks!

**Additional context**

http://beta.plantary.art -- after purchase of an NFT we want to redirect the user to the link for that NFT.

**Comment by ilblackdragon** [comment]
Indeed an annoying issue.
I agree that we should pass options, but it will take some passing:
 - Currently passes https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L206 `window.location.href` replace to `options.callbackUrl`
 - in `wallet-account.ts` and `account.ts` (https://github.com/near/near-api-js/blob/master/src/account.ts#L141) should take `options`
 - `functionCall` in `Account` should take `options` (https://github.com/near/near-api-js/blob/master/src/account.ts#L276)
 - https://github.com/near/near-api-js/blob/master/src/contract.ts#L48 should take options similar how `viewMethods` above do.

PR is welcome!

**Comment by myklemykle** [comment]
OK, that's about what I thought it would take.  All of those methods seem like they'll be able to hand another (optional) argument at the end, so it looks like an easy refactor.  Not sure when I'll get to this but we'll need it fixed for launch so hopefully soon.

**Comment by mikedotexe** [comment]
We're adding this to a board for the shared tool team right now. Thanks Mykle for bumping this and Illia for fleshing out the details.

**Comment by kcole16** [comment]
Wallet API NEP which this should conform to: https://github.com/near/NEPs/blob/c1947120f6b651bb1d0678ab1805c4628a418db4/text/0000-walletapi.md

**Comment by mehtaphysical** [comment]
As @ilblackdragon mentioned above, we'll have to pass information from `contract.changeMethod` -> `account.functionCall` -> `account.signAndSendTransaction`. All of these functions are getting to have a lot of parameters that they take. And, in the case of `account.functionCall` in particular, they take a few optional parameters.

My proposal is to start deprecating these methods that take many parameters in favor of them taking a single object. This has three main advantages:

* easier to leave off optional parameters
* easier to add new parameters in the future
* easier for developers to use because order of parameters won't matter

The refactor should happen in such a away that the old uses still work, but developers receive a message to start using an object instead. I'm thinking somthing like:

```ts
class Account {
 //.....
    async functionCall(props: FunctionCall): Promise<FinalExecutionOutcome>;
    async functionCall(contractId: string, methodName: string, args: any, gas?: BN, amount?: BN): Promise<FinalExecutionOutcome> 
    async functionCall(...args: any[]): Promise<FinalExecutionOutcome> {
        if(typeof args[0] === 'string') {
            return this.functionCallV1(args[0], args[1], args[2], args[3], args[4]);
        } else {
            return this.functionCallV2(args[0]);
        }
    }

    private functionCallV1(contractId: string, methodName: string, args: any, gas?: BN, amount?: BN): Promise<FinalExecutionOutcome> {
        // Set deprecation warnings etc...
        args = args || {};
        this.validateArgs(args);
        return this.signAndSendTransaction(contractId, [functionCall(methodName, args, gas || DEFAULT_FUNC_CALL_GAS, amount)]);
    }

    private functionCallV2({ contractId, methodName, args, gas = DEFAULT_FUNC_CALL_GAS, attachedDeposit }: FunctionCall): Promise<FinalExecutionOutcome> {
        this.validateArgs(args);
        return this.signAndSendTransaction(contractId, [functionCall(methodName, args, gas, attachedDeposit)]);
    }
}
```

How does this sound @vgrichina?
