### ISSUE TITLE
Missing RPC methods

### ISSUE THREAD

**Issue by mehtaphysical** [near/near-api-js#532]
There are a bunch of missing RPC methods. For example `EXPERIMENTAL_changes`. Should these be added?

Here is a list of all RPC methods: https://github.com/near/nearcore/blob/master/chain/jsonrpc/src/lib.rs#L266

**Comment by thisisjoshford** [comment]
> There are a bunch of missing RPC methods. For example `EXPERIMENTAL_changes`. Should these be added?
> 
> Here is a list of all RPC methods: https://github.com/near/nearcore/blob/master/chain/jsonrpc/src/lib.rs#L266

I don't see any reason why we should not have all RPC endpoints available in `near-api-js`. IMO, adding these endpoints will create a more complete library. :)
