### ISSUE TITLE
Loading a contract when logged out + handling logged out flow

### ISSUE THREAD

**Issue by ckshei** [near/near-api-js#55]
If the user is logged out: 
near.account() won't work with an empty string
nearlib.Contract() won't work without an account

Thus you can't call contract view functions if the user is not logged in, which isn't good UI (i.e. for guestbook you can't see guestbook entries if you're not logged in). 

Desired behavior:
Contract view functions should be able to be called when logged out

Discussion: 
Potentially creating some sort of 'read-only' account as a placeholder for guest

**Comment by chadoh** [comment]
@vgrichina I believe this was fixed at some point, as Guest Book now shows messages when you are not yet logged in. Can you confirm and identify the PR that addressed this issue?
