### ISSUE TITLE
Add option to remove console logs

### ISSUE THREAD

**Issue by FranklinWaller** [near/near-api-js#564]
**Is your feature request related to a problem? Please describe.**
Near-api-js logs a transaction status. It feels more like debug info that has been left in. 

**Describe the solution you'd like**
Add option that allows you to set debugging logs

**Additional context**
![Screenshot 2021-04-20 at 11 21 47](https://user-images.githubusercontent.com/5691892/115371816-99c19b00-a1ca-11eb-83ba-f9b3d99eb465.png)

**Comment by FranklinWaller** [comment]
Did a quick implementation of it. Have not tested it but is this something that's ok for you guys? https://github.com/FranklinWaller/near-api-js/commit/08f1546d2bb639ef4d5fdb0434ea790a81ec561d

**Comment by mehtaphysical** [comment]
I agree. It would be nice to be able to configure whether messages are logged.

I wonder if the approach should be to add a `Logger` interface or abstract class. Have a default implementation that uses `console.*` for logging. But would allow people to provide their own logger that, say, sends logs to sentry, logentries, etc.

**Comment by raymondfeng** [comment]
> I wonder if the approach should be to add a Logger interface or abstract class. Have a default implementation that uses console.* for logging. But would allow people to provide their own logger that, say, sends logs to sentry, logentries, etc.

+1 to define a `Logger` interface (possibly expose some contextual args for the logging) and allow an option in `Near` constructor to customize the logger.

**Comment by FranklinWaller** [comment]
Any status update on this issue?
