### ISSUE TITLE
Can we allow the wallet to provide decryption capabilities

### ISSUE THREAD

**Issue by unix** [near/near-api-js#566]
**Is your feature request related to a problem? Please describe.**

If we allow NEAR APIs (and `near-api-js`) to provide the private key to string decryption, we can have more imaginative DApps, similar to the [eth_decrypt RPC](https://docs.metamask.io/guide/rpc-api.html#eth-decrypt) interface provided by MetaMask.

**Describe the solution you'd like**

The user can decrypt an existing `string` by calling `near-api-js`, which also allows the user to provide the encrypted public key to encrypt the `string`:

```
const sign = () => {
  wallet.requestDecrypt(
    "example-contract.testnet", 
    "string..." ,
    "http://YOUR-URL.com/success", 
    "http://YOUR-URL.com/failure"
    )
}
```

If developers can request users to decrypt strings with private keys through the API, the community may have more practical applications based on this, such as decentralized and fully encrypted email systems based on NEAR, etc.

I'm not quite sure if NEAR is designed to support this feature, just offering it as a suggestion to the community.

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by mehtaphysical** [comment]
Thanks for this! We've discussed this sort of functionality in the past, but have decided against using account keys to encrypt/decrypt arbitrary messages. Here is a place this has been discussed: https://github.com/near/nearcore/issues/2833
