### ISSUE TITLE
Make signAndSendTransaction functionality public

### ISSUE THREAD

**Issue by mehtaphysical** [near/near-api-js#568]
Right now the `account.signAndSendTransaction` method is protected. The expectation being that a developer should use the `functionCall`, `createAndDeployContract`, `sendMoney`, etc methods.

It would be nice to open up that functionality so that developers can send their own custom action bundles.

We cannot just remove the `protected` accessor because that would be a breaking change (every implementation of `Account` would have to update). Instead we should make another method that exposes this functionality publicly. But, what should this method be called? `signAndSendTransaction` is already taken. Maybe `sendBundledActions`?

**Comment by mehtaphysical** [comment]
This will be fixed by #557

**Comment by FranklinWaller** [comment]
It looks like it's still unavailable. Weird because the methods are in the cookbook: https://docs.near.org/docs/api/naj-cookbook#batch-transactions

**Comment by mohitxskull** [comment]
I am using typescript and the method is protected
