### ISSUE TITLE
Remove use of internal "fetch" and "fetchJson" functions.  Add proper dependencies instead

### ISSUE THREAD

**Issue by stunney** [near/near-api-js#573]
The fetch and fetchJson functions in the web.js files are inadequate for use in CORS-enabled environments (most public sites).

Please just depend on the packages.

**Comment by mehtaphysical** [comment]
Can you expand on this? What inadequacies are you experiencing?

**Comment by stunney** [comment]
lack of CORS support, only GET/POST are supported (not head, patch, put, delete) it seems from the code.

forcing developers to use an alias for the function isn't helpful either when we want to use our own impl.

**Comment by mehtaphysical** [comment]
That function is for making JSON RPC requests to a NEAR node. It’s not really meant for general use.

What is your use case?

**Comment by mehtaphysical** [comment]
@stunney any update on this? I'm still not sure what the use case for supporting more methods is.

**Comment by stunney** [comment]
I think the issue here is that this fetch method is out of date.  Why not include the standard fetch and fetch-json npm modules?

when I try to include fetch or fetch-json myself, these functions are causing naming ambiguity issues when running the code.

**Comment by mehtaphysical** [comment]
We use the `fetch` function that is built into the browser in browser contexts and use `node-fetch` when in a node context.

Are you importing the `near-api-js` `fetchJson` function into your code? Can you provide a code snippet of where this is causing issues?

**Comment by vikinatora** [comment]
Closing as issue isn't relevant anymore.
