### ISSUE TITLE
KeyPair fails to verify its own signature

### ISSUE THREAD

**Issue by raymondfeng** [near/near-api-js#574]
**Describe the bug**

KeyPair fails to verify its own signature. In my case, the secret key is generated from `{getED25519Key}@toruslabs/openlogin-ed25519`.

```ts
    const secretKey = "24SvBemXNBThfSknnaRtEbjNemt6xepe2mNVqc7Np2fkUdJSfnz4dX5BGp4QyFVWeXewqW44uDGKVVXaSd4ovDRJ";
    const kp = KeyPair.fromString(secretKey);
    const msg = Buffer.from('123');
    const signature = kp.sign(msg).signature;
    expect(kp.verify(msg, signature)).to.be.true(); // This fails
```

If the secret key is generated using `KeyPair.fromRandom('ed25519')`, the verification works.

**To Reproduce**

Run the test above.

**Expected behavior**

Expect verify() to return `true`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by raymondfeng** [comment]
CC @mattlockyer

**Comment by mattlockyer** [comment]
I get the same thing using this string: '24SvBemXNBThfSknnaRtEbjNemt6xepe2mNVqc7Np2fkUdJSfnz4dX5BGp4QyFVWeXewqW44uDGKVVXaSd4ovDRJ'

![image](https://user-images.githubusercontent.com/321340/116818214-1899ca80-ab1f-11eb-8bd4-346164ab7204.png)

But when I switch the string to anything generated from KeyPair.fromRandom('ed25519') I don't.

![image](https://user-images.githubusercontent.com/321340/116818320-a7a6e280-ab1f-11eb-8d91-7934f305a370.png)

**Comment by mehtaphysical** [comment]
I think this may be an issue with the secretKey. I've tried using it directly with tweetnacl and it doesn't work:

```ts
import nacl from 'tweetnacl';
import bs58 from 'bs58';


const secretKey = '24SvBemXNBThfSknnaRtEbjNemt6xepe2mNVqc7Np2fkUdJSfnz4dX5BGp4QyFVWeXewqW44uDGKVVXaSd4ovDRJ';
const msg = Buffer.from('123');

const kp = nacl.sign.keyPair.fromSecretKey(bs58.decode(secretKey));
const signed = nacl.sign(msg, kp.secretKey);
console.log(nacl.sign.open(signed, kp.publicKey)); // returns null
```

This does work with a different `secretKey` for example: `4WCgt4e3biVJfgD3fsiMnKaPFQZKhxrvzN1St1V9f4DF5TwTomcmqezjCekaQcYbm1XvJUqvs1KeJUzJzi95jfpM`

**Comment by raymondfeng** [comment]
Yeah, that's strange. Can KeyPair reject such secret keys? It would be interesting to find out why.

**Comment by raymondfeng** [comment]
Please note that the secret was generated by https://www.npmjs.com/package/@toruslabs/tweetnacl-js, which seems to be a wrapper of https://github.com/dchest/tweetnacl-js.

**Comment by raymondfeng** [comment]
```js
var l = tweetnacl_js_default.a.lowlevel;
function getED25519Key(privateKey) {
  var privKey;

  if (typeof privateKey === "string") {
    privKey = Buffer.from(privateKey, "hex");
  } else {
    privKey = privateKey;
  } // Implementation copied from tweetnacl


  var d = new Uint8Array(64);
  var sk = new Uint8Array([].concat(toConsumableArray_default()(new Uint8Array(privKey)), toConsumableArray_default()(new Uint8Array(32))));
  var pk = new Uint8Array(32);
  var p = [l.gf(), l.gf(), l.gf(), l.gf()];

  for (var i = 0; i < 32; i += 1) {
    d[i] = sk[i];
  } // eslint-disable-next-line no-bitwise


  d[0] &= 248; // eslint-disable-next-line no-bitwise

  d[31] &= 127; // eslint-disable-next-line no-bitwise

  d[31] |= 64;
  l.scalarbase(p, d);
  l.pack(pk, p);

  for (var _i = 0; _i < 32; _i += 1) {
    sk[_i + 32] = pk[_i];
  }

  return {
    sk: Buffer.from(sk),
    pk: Buffer.from(pk)
  };
}
```

**Comment by mattlockyer** [comment]
@mehtaphysical I ran near-api-js locally and updated tweetnacl to 1.03 (matching the version from Toruslabs)

Didn't make a difference using the key from the original post in this issue.

**Comment by mehtaphysical** [comment]
@raymondfeng do you agree that this is an issue with the secret in the initial example and not an issue with `near-api-js`?

**Comment by mehtaphysical** [comment]
@raymondfeng makes sense. I’m going to change the label from bug to devx 

I’m also not sure the best way to do thi since tweetnacl is ok with it up until you try to verify. So does that mean the check is to sign and then verify a message? Is there a better way?

**Comment by mattlockyer** [comment]
TBH the fault lies with tweetnacl on this one. Their checks for keys are basic length etc. Allowing the Developer to create instances they think are valid.

One idea:
We could wrap a lazy async signature verify that will console warn in near-api-js, so at least you get a heads up that the key doesn't look valid.

Since speed is not our issue here we could do a sync check, but I'm wary of blocking execution and throwing exceptions here. Not sure what's best.

Do we know for a fact the key is 100% invalid for anything even NEAR TXs?

**Comment by raymondfeng** [comment]
@mattlockyer @mehtaphysical I did a bit research and found out that `Torus` does not use https://github.com/dchest/tweetnacl-js/blob/master/nacl-fast.js#L1917 directly. Their implementation is very similar but it's missing the step on https://github.com/dchest/tweetnacl-js/blob/f1ec050ceae0861f34280e62498b1d3ed9c350c6/nacl-fast.js#L1923.

I'm asking Torus team to use `crypto_sign_keypair` instead.

I'm good to close this issue as we now have some understanding of the root cause.

**Comment by mattlockyer** [comment]
Fantastic! Thanks for digging @raymondfeng 👍👏
