### ISSUE TITLE
Default Gas differs from near-shell

### ISSUE THREAD

**Issue by willemneal** [near/near-api-js#584]
**Describe the bug**
Detailed [here](https://stackoverflow.com/questions/67411094/executionerror-exceeded-the-prepaid-gas-when-called-from-front-end/67422237#67422237), this library's default gas value is more than 3 times less than near-shell.

**Comment by volovyk-s** [comment]
I assume it should be sage to increase it in `near-cli`. We have it in two places, `call.js` and `evm-call.js`.

**Comment by volovyk-s** [comment]
Plan:
- [ ] merge https://github.com/near/near-api-js/pull/586
- [ ] release new `near-api-js` version
- [ ] update `naj` version in https://github.com/near/near-cli/pull/744 and merge
