### ISSUE TITLE
Investigate and fix what's needed to change in `near-api-js` now that nonces have changed.

### ISSUE THREAD

**Issue by mikedotexe** [near/near-api-js#585]
Hey @Mike Purvis | NEAR @Matt Lockyer | NEAR with the new release (on testnet now) we fixed the access key nonce issue. More concretely, when you add an access key, its nonce will automatically be set to (current_block_height - 1) * 1_000_000 . As discussed before, this should not break anything, but just want to let you know in case you notice that something does not work as expected

This ticket may include pinging Frol and/or Bowen to see what has changed.

**Comment by mehtaphysical** [comment]
This is covered by #587

**Comment by ymyroniuk** [comment]
> This is covered by #587

Hi. I have problem too often what nonce not increased and we got an error and the transaction is sent after and we saw bug about some time means there are too many parallel requests with the same access key. How can i resolve it? Maybe do you know?
