### ISSUE TITLE
Ability to attach custom headers in the RPC requests

### ISSUE THREAD

**Issue by chefsale** [near/near-api-js#591]
Use case I need this for is user RPC authentification. The user would pass an AuthorizationToken: <SECRET> in the headers to authenticate with RPC.

**Comment by volovyk-s** [comment]
@chefsale do we have that functionality on the JSON RPC side?
Can you please elaborate a bit with the use case, because I'm not sure if it's something that will play well with the existing concept of JSON RPC, private keys, view calls etc.
cc @frol

**Comment by frol** [comment]
You can extend the provider and specify it when you create a connection: https://github.com/near/near-api-js/blob/master/src/connection.ts#L40

That extended provider can just extend the [`JsonRpcProvider` class](https://github.com/near/near-api-js/blob/master/src/providers/json-rpc-provider.ts#L52), and override `sendJsonRpc` which is used by all the rest methods

**Comment by frol** [comment]
However, it might be a good idea to have this use-case covered in near-api-js natively since it might need to be integrated in near-cli

**Comment by chefsale** [comment]
@frol Yes, i think just adding an additional parameter header which is empty by default to the provider would be a way to go. In the end the JSON-RPC is still again using HTTP if this is what you mean by natively?

**Comment by frol** [comment]
Yes, that is what I meant
