### ISSUE TITLE
Delete hacks related to Error Types

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#611]
Delete [https://github.com/near/near-api-js/blob/master/src/utils/rpc_errors.ts#L88](https://github.com/near/near-api-js/blob/master/src/utils/rpc_errors.ts#L88) and other hacks related to Error handling and types when they will be available on `near-core`.

**Comment by frol** [comment]
Just for tracking purposes, this issue can be addressed once https://github.com/near/nearcore/issues/2976#issuecomment-852369972 is implemented and rolled out to all our networks.
