### ISSUE TITLE
Fix demonstration on how to do a "view" call

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#612]
Add an easy way for someone to do a "view" call without having to set up a near object with an account, etc. Something like nearAPI.view(acc, funcName, args)); so it does not have a dependency on the Account. Probably should be a separate function. Should not be a breaking change.

**Comment by mikedotexe** [comment]
I believe we meant to add this into the Quick Reference or Cookbook but possibly missed it:
https://github.com/near/near-api-js/issues/483#issuecomment-833898431

**Comment by mikedotexe** [comment]
This doesn't work:
https://github.com/near/near-api-js/blob/26b3dd2f55ef97107c429fdfa704de566617c9b3/examples/cookbook/utils/get-state.js

when running `node get-state.js`. Error:

>Parse error: Failed parsing args: invalid type: sequence, expected struct RpcQueryRequest

**Comment by volovyk-s** [comment]
@mikedotexe can you please clarify what do you want to fix in this issue? Originally it was intended to add a simpler way to make `view` calls. Now looks like it's more about fixing the `get-state.js` example.
BTW, `get-state.js` forks on my PC. Tested on `Node` 12 - 16.
Should we just close it then?

**Comment by volovyk-s** [comment]
That example works now. Closing this issue.
