### ISSUE TITLE
Near.account() should be a sync method

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#614]
Near.account() should be a sync method that returns Account. It's a breaking change for people who are using `Promises`. Probably we should deprecate the current implementation first.

**Comment by Rishabhraghwendra18** [comment]
Hi @volovyk-s . Is this issue still open ?

**Comment by volovyk-s** [comment]
Not at the moment. It's a one line fix and we will merge it with 1.0 release.

**Comment by Rishabhraghwendra18** [comment]
ok.. if you don't mind I can make a PR for this one line fix
