### ISSUE TITLE
Minimize the size of near-api-js

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#615]
Looks like our `naj` releases contain lots of redundant files like configs and tests. We should exclude them and reduce the size of the library.
Nice to have, but can be a separate issue: examine dependencies deletion and other ways to reduce the size of the library.

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s may I help you in this ?

**Comment by volovyk-s** [comment]
I need to make some additional tests on this issue. I will assign it to myself for now.
Consider this issues: https://github.com/near/near-cli/issues/317
And this one: https://github.com/near/near-cli/issues/762
The second one is only if you have a Ledger hardware wallet and willing to dig deep into C and JS code.

**Comment by Rishabhraghwendra18** [comment]
Ok..no problem.
Are you working on `issue #317`.
No I don't have any ledger hardware right now

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18  Please, leave a comment in  https://github.com/near/near-cli/issues/317, I can not assign you until then.
