### ISSUE TITLE
Access Key does not exist does not relay an accurate message

### ISSUE THREAD

**Issue by zcstarr** [near/near-api-js#618]
When you sign a transaction, with a pub/priv key pair , that does not have an explicit named account. If accountId used to sign the transaction, does not have an accessKey that matches the public key in the keystore, it does not properly throw a more informed error message. It throws "no matching key pair found in InMemorySigner(InMemoryKeyStore)

create a KeyPair set the keystore to an existing accountId with a random private/public key sign a transaction that using that accountId

 _**Expected behavior**_ I would expect access key not found error, vs key pair not found in Keystore. How do people feel about allowing throwing there, I'm not familiar with where findAccessKey is really used in the code base/codebases. Happy to submit a pr for this, it's not critical or blocking just noticed it.

Another alternative which might be less drastic is to simply change the error message to something like "Could not find access key, check keystore entries or account id access keys". It's rough wording but maybe just improved language is the biggest bang for your buck here.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/173187/121125271-23f5ab00-c7db-11eb-8714-c614d1a27332.png](https://user-images.githubusercontent.com/173187/121125271-23f5ab00-c7db-11eb-8714-c614d1a27332.png))

**Comment by volovyk-s** [comment]
@zcstarr can you please provide code snippets? I'm struggling to understand this issue. If the fix is short you can add a PR and we will check the changes.

**Comment by janewang** [comment]
@zcstarr Are you interested in submitting a PR for this? If not, we will update the error message. Cheers

**Comment by zcstarr** [comment]
@janewang feel free to take this on. Thanks!
