### ISSUE TITLE
"Transaction has expired" Error on TestNet when creating accounts

### ISSUE THREAD

**Issue by think-in-universe** [near/near-api-js#626]
**Describe the bug**
As reported by several developers, they often met "Transaction has expired" error when creating accounts on TestNet.

**To Reproduce**
The issue happens randomly, and there's no deterministic way of reproducing the issue. 

Below are how developers met the issue when :

1. create new testnet accounts with wallet and error pops up;
2. create accounts with NEAR CLI.

**Expected behavior**
Creating accounts should be stable on testnet

**Screenshots**
Create account with NEAR CLI, and met the error below by developers:

![image](https://user-images.githubusercontent.com/46699230/122701332-935da700-d27f-11eb-95bb-85a26506b8b1.png)

**Version (please complete the following information):**
- testnet

**Additional context**
This may also be related to the recent change to testnet account creation https://github.com/near/near-contract-helper/pull/447

**Comment by frol** [comment]
@mikedotexe @vgrichina @volovyk-s What do you think?

**Comment by volovyk-s** [comment]
@frol we have this error in our schema: https://github.com/near/near-api-js/blob/6e36ba2c3eb896cd72b5da8690d703cc5b70f693/lib/generated/rpc_error_schema.json#L610
So probably the origin of this error is not `near-api-js`.
I'm not sure if I fully understand why this error is thrown, like.. what is expired?

**Comment by frol** [comment]
@volovyk-s it is a similar error to `InvalidNonce`. Let me show the `SignedTransaction` structure that gets submitted to the blockchain:

```rust
SignedTransaction {
    transaction: Transaction {
        actions: [
            Transfer(
                TransferAction {
                    deposit: 2000000000000000000000000,
                },
            ),
        ],
        receiver_id: "qq.frol4.testnet",
        signer_id: "frol4.testnet",
        // public key must be registered as a signer's FullAccess key, and its corresponding private key is used to sign the hash of this transaction to produce the `signature` (see below)
        public_key: ed25519:3oN25HE9tf9YUGXQyXCFB2rEtpomijG8ghVV2JvrA4zJ, 
        // nonce should monotonically increase with each transaction submitted for the given access key
        nonce: 19,
        // this is a hash of some recent block to ensure that the transaction is constructed for the specific chain thus avoiding replay attack when you have the same account ids on testnet and mainnet and someone just re-sends your transaction from testnet to mainnet
        block_hash: `27hfTxUF3wCgV5U16uvhrEQRZmbDHQkVh25Hb8tf1e7i`,
    },
    hash: `2DLtZEMeG1wp3wyxgXpFmrhfe1Xm7YN1VP8LNoNhC3FG`,
    size: 131,
    signature: ed25519:byRKymkv5KThHc9Mv1zjtyKf8N3CRigp5NRCm8hqqSWxZMfHEPGkCQV6fvCTR2xX98C8g8iv7Hic7Vc6WF6uX9H,
}
```

You get [`InvalidNonce`](https://github.com/near/nearcore/blob/a6bf293727fd5189dee19a7b45514d09cf7c0085/core/primitives/src/errors.rs#L114-L115) when the nonce is less than the latest observed value on the blockchain (e.g. you send two transactions concurrently with the same nonce, only one will be applied and another will receive `InvalidNonce`)

You get [`InvalidChain`](https://github.com/near/nearcore/blob/a6bf293727fd5189dee19a7b45514d09cf7c0085/core/primitives/src/errors.rs#L140-L141) when the `block_hash` is not part of the current chain.

You get [`Expired`](https://github.com/near/nearcore/blob/a6bf293727fd5189dee19a7b45514d09cf7c0085/core/primitives/src/errors.rs#L142-L143) when the `block_hash` is of the block that has a height that is [more than `validity_period` blocks](https://github.com/near/nearcore/blob/c7d8fe898864ebf3b498c87954e0d1a38ab4e2c9/chain/chain/src/store.rs#L469) away from the tip of the chain ([on mainnet and testnet the `transaction_validity_period` is set to 86400](https://github.com/near/nearcore/blob/c7d8fe898864ebf3b498c87954e0d1a38ab4e2c9/neard/res/mainnet_genesis.json#L233))

**Comment by volovyk-s** [comment]
Updates from discussion with @frol:
- `Expired` error can be thrown from the outdated node (1 day +) @bowenwang1996 is this situation possible? Should we restrict validation from outdated nodes?
- we can handle it the same way we are handling `InvalidNonce`, and that should be the fix for this issue.

**Comment by bowenwang1996** [comment]
> Expired error can be thrown from the outdated node (1 day +) @bowenwang1996 is this situation possible? Should we restrict validation from outdated nodes?

Yes if near-api-js pulls the nonce from a node that is very out of sync. Maybe we should check that the node is healthy first (query the health endpoint).

**Comment by frol** [comment]
@bowenwang1996 you cannot guarantee that after you do the health check your next RPC call will land on the same node, thus, we should just retry here (we could figure out the latest block from the `status` endpoint and checking that the node we reached out returns `syncing: false`, so we don't force user to re-sign the transactions with ledger unnecessary number of times)
