### ISSUE TITLE
Inconsistent API between functionCall and viewFunction.

### ISSUE THREAD

**Issue by mattlockyer** [near/near-api-js#627]
***Describe the bug***
 Same as title.

***To Reproduce***
 Try viewFunction with syntax like this:
 ```
 const token = await contractAccount.viewFunction({
 contractId,
 methodName: 'nft_token',
 args: 

 { token_id, } 

})
 ```

***Expected behavior***
 Expect them both to accept the POJO syntax e.g. 

 { contractId, methodName, args, ...} 

***Screenshots***
 !<span class="error">[image]</span>([https://user-images.githubusercontent.com/321340/123719335-22e1f780-d836-11eb-84f6-0f7f8dffd83c.png](https://user-images.githubusercontent.com/321340/123719335-22e1f780-d836-11eb-84f6-0f7f8dffd83c.png))

**Comment by zcstarr** [comment]
Just going to second this, I hit the same issue. It's killer when your'e trying to figure out what's wrong, you end up rolling the dice and going to the deprecated version.
