### ISSUE TITLE
Missing keyStore in connect raise an error whereas it should not 

### ISSUE THREAD

**Issue by zurgl** [near/near-api-js#640]
**Describe the bug**
The claim, from the official [doc](https://near.github.io/near-api-js/modules/connect.html)

> Connect to NEAR using the provided configuration.
> ConnectConfig.networkId and ConnectConfig.nodeUrl are required

is not verified.
 
**To Reproduce**
run this test case:
```javascript
(async () => {
    const near = await connect({
        networkId: "testnet",
        nodeUrl: "https://rpc.testnet.near.org",
    });
    return 'connected'
})()
    .then(console.log)
    .catch(console.error)
```
**Expected behavior**
This test should pass, but in fact we have to provide a keystore otherwise it fail.

**logged error**
```bash
TypeError: Cannot read property 'keyStore' of undefined
    at new Near (xxxxx/test/node_modules/near-api-js/lib/near.js:34:105)
...
```

**Fix**
Applying the following patch to `lib/near.js` at line 34
```javascript
            signer: config.signer || { type: 'InMemorySigner', keyStore: config.keyStore || config.deps?.keyStore }
```
precisly `config.deps?.keyStore` replacing `config.deps.keyStore`

Fix the issue

**Comment by volovyk-s** [comment]
Closing this issue since it affects deprecated API's. More info in the linked PR.
