### ISSUE TITLE
Investigate the deletion of dist/near-api-js.js file

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#644]
We need to investigate the deletion of `near-api-js.js`. Should we keep both `near-api-js.js` and `near-api-js.min.js`?
 According to this discussion, we need to delete `near-api-js.js` before 1.0 release: [https://github.com/near/near-api-js/pull/631](https://github.com/near/near-api-js/pull/631)

**Comment by Rishabhraghwendra18** [comment]
I am working on this issue
