### ISSUE TITLE
Utility "calculate-gas" is broken

### ISSUE THREAD

**Issue by mikedotexe** [near/near-api-js#656]
When trying to run `node calculate-gas.js` in `examples/utils` get error:

UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

This is after changing "near-example.testnet" to something like "mike.testnet" which is a valid account in the home directory.

**Comment by ChaoticTempest** [comment]
This seems to be working again:
```
❯ node utils/calculate-gas.js   
------------------------------------------------------------------------ 
RESULTS for: [ addMessage ] called on contract: [ guest-book.testnet ]
------------------------------------------------------------------------ 
Gas Burnt     |  6516499018425
Tokens Burnt  |  0.00024279813702180.00038653350857070
------------------------------------------------------------------------ 
```
so closing for now. @mikedotexe feel free to reopen if this is still an issue
