### ISSUE TITLE
Callback url for payable function page redirect

### ISSUE THREAD

**Issue by amiyatulu** [near/near-api-js#680]
When I use payable method, the page redirects to the wallet to approve the amount, but after the redirection, it returns to the old page.

Here, the reactjs code:

```
onSubmit={async (values, actions) => {
  try {
        const data = await nearvar.contract.add_liquidity({"tokens": values.buy.toString(), "account_id": "amiyarust.testnet"}, 95000000000000, 500)
        // Page redirects here. Code below is not run. 
        actions.setSubmitting(false)
        history.push(`/hello`)
    } catch (e) {
       console.error(e)
   }

```

It will be nice if one can pass a callback url while calling the function, so that page redirects to the new page rather than old page, just like payment gateways e.g. paypal.

**Comment by volovyk-s** [comment]
@amiyatulu looks like we [already have it](https://github.com/near/near-api-js/blob/master/src/contract.ts#L74)
@thisisjoshford should we add it to the docs [here]( https://github.com/near/near-api-js/blob/master/src/contract.ts#L74)?
