### ISSUE TITLE
URGENT fix broken dependency please

### ISSUE THREAD

**Issue by mattlockyer** [near/near-api-js#688]
**Describe the bug**

NAJ relies on:
https://www.npmjs.com/package/error-polyfill

which relies on unmaintained:
https://www.npmjs.com/package/u3

**which has the bug:**
https://github.com/inf3rno/u3/issues/3

when bundling with modern bundlers e.g. parcel 2:
https://github.com/parcel-bundler/parcel/releases/tag/v2.0.0-rc.0

**To Reproduce**
Try to bundle NAJ with 
https://github.com/parcel-bundler/parcel/releases/tag/v2.0.0-rc.0

**Expected behavior**
It works.

**More info**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Delete_in_strict_mode

**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Additional context**
URGENT please, breaks all my builds and I have to patch this deep dep across every repo

**Comment by willemneal** [comment]
@vgrichina What is the error-polyfill used for?  Why do we need v8 like errors in the browser?

**Comment by MaximusHaximus** [comment]
This has been a topic of discussion before in #598 

In a nuthshell, in order to remove the polyfill, we need to re-implement `http-errors` from my understanding -- see comment:
https://github.com/near/near-api-js/pull/598#issuecomment-844500100

**Comment by mattlockyer** [comment]
I removed it according to @chadoh direction in the above PR and it passes all tests?

https://github.com/near/near-api-js/pull/689

I have a fix and response from u3 maintainer here:
https://github.com/inf3rno/u3/issues/3

**Comment by mattlockyer** [comment]
Update:

https://github.com/inf3rno/error-polyfill/pull/36 pending

Because @inf3rno was awesome and did:

https://github.com/inf3rno/u3/releases/tag/v0.1.1

**Comment by mattlockyer** [comment]
Resolved by https://github.com/near/near-api-js/pull/689

Bump error-polyfill version which bumps u3 version.

https://github.com/inf3rno/error-polyfill/commit/d6286daba0380eff28f22e4cd8272e8a43ca9362

and

https://github.com/inf3rno/u3/commit/61af796b6a3d98bdb0f04461530b7f6338228095

Thanks to https://github.com/inf3rno
