### ISSUE TITLE
account.nonce getter

### ISSUE THREAD

**Issue by DanielRX** [near/near-api-js#69]
`get nonce(): number { return this._accessKey.nonce; }`

Something as simple as this would allow the nonce to be retreived from the account object, which would allow some more complex "sign then send" functions

**Comment by chadoh** [comment]
@DanielRX would #52 also be an acceptable way to address this need?

**Comment by DanielRX** [comment]
No? That wouldn't allow me to access the once at all. It's not for the sake of returning the tx

**Comment by mehtaphysical** [comment]
Is this still an issue? Can get the nonce with:

```js
const { nonce } = await account.findAccessKey();
```
