### ISSUE TITLE
Fix Danger (in a safe way)

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#699]
- [x] Add GitHub bot acc to 1Password
- [x] Add Token
- [x] Make sure that Danger and test work

**Comment by mikedotexe** [comment]
Getting this error with CI:
>Without an api token, danger will be unable to comment on a PR

**Comment by mikedotexe** [comment]
bump

**Comment by volovyk-s** [comment]
Added passwords to 1Pass, discussing key access scopes with @chefsale now.
