### ISSUE TITLE
Add a git hook to build the js files before commiting

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#701]
We are often forgetting to run `yarn build` before the push. Let's fix it once and for all.

**Comment by Rishabhraghwendra18** [comment]
is this issue still open ?

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18  Yes, it is. You can work on it.

**Comment by Rishabhraghwendra18** [comment]
Ok.. Thanks . I will make a PR for this today

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s do I need to install a dev package like `Husky` for Git Hooks because I can't find such any package in `package.json`

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18 please, do all the necessary work, but do not push package.json and lock files. I will add this dependency myself of we will decide to merge this your PR.

**Comment by Rishabhraghwendra18** [comment]
ok sure
