### ISSUE TITLE
Refresh the page after wallet signOut

### ISSUE THREAD

**Issue by EdoWahdana** [near/near-api-js#707]
When I tried to sign out the connected wallet from testnet, it did successfully but I didn't get any notification or else. 
Perhaps the best approach for this is to refresh the current web page so the user doesn't have to do any checking after signing out.

**Comment by SteMak** [comment]
I don't think that refreshing page after singout is a good idea:
- For example, imagine an SPA where no page reloading should appear.

If you want to have some notion about signing out you can do in such way:
```js
const signOutNear = () => {
  walletConnection.signOut()
  document.dispatchEvent(new Event("NearSignedOut"))
}

document.addEventListener("NearSignedOut", () => {
  alert("Oh no! We should reload the page immediately :(")
  location.reload()
}

signOutButton.onclick = signOutNear
```

It is not difficult to reload the page, more difficult is prevent reloading)

**Comment by EdoWahdana** [comment]
That's a great solution. I was curious if there is a function to handle such a thing without writing listener by ourselves, Anyways, I'm closing this one. Thanks
