### ISSUE TITLE
Add support for the new staking action 

### ISSUE THREAD

**Issue by posvyatokum** [near/near-api-js#708]
All dev tools are updated to support the new staking action (Shared with Developer Platform)

Part of https://airtable.com/apprrAlfLE1QI6gao/tbl9h3jXf56F4lAql/viw1VzQz6DtES5vbR/rec7i5zgeHPtd6lv7?blocks=hide

**Comment by janewang** [comment]
Based on updated Q4 OKRs, this issue is removed from NodeX Q4 board 
cc @posvyatokum  @bowenwang1996

**Comment by volovyk-s** [comment]
I'm not sure what this issue is all about. Please, reopen if needed with proper explanation (no external links).
