### ISSUE TITLE
Please sunset redirects in favor of a signing service or similar.

### ISSUE THREAD

**Issue by SteMak** [near/near-api-js#713]
***Problematic***
 Approving of transactions or signing in lefts track in the history api of browser.
 In such way, when user trying go back, he appears with this tracks. Unexpirienced user can be confused and even make transaction twice
 Example: on most of mobile devices backbutton is in the bottom of the screen and can be triggered by chance. User can think that something went wrorg and needs to try make transaction again
 Another example: user is actively searching in a dapp, trigger "sign in" and then wants go back to previous dapp page (by clicking backbutton) and he appear with the signing form again!

***How I see the solution***
 I order to keep history dapps holistic we shouldn't redirect to the "caller page", we should use `history.back(-count_of_pages_we_have_used_after_call)`
 Another idea: open transaction confirmation in new tab

In both ways history of using a dapp won't be devided by confirming transactions and other blockchain-related events

**Comment by vikinatora** [comment]
Hi @SteMak, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this issue seems no longer relevant. Please let me know if that's not the case; otherwise, I'll proceed to close the issue in 5 days.
