### ISSUE TITLE
TypeScript + Contract Methods = Error (Property Does Not Exist On Type Contract)

### ISSUE THREAD

**Issue by modagavr** [near/near-api-js#719]
**Describe the bug**
contract.view_method_name() -> Property 'view_method_name' does not exist on type 'Contract'

**To Reproduce**
1. Connect to a node
2. Create new Contract()
3. Call some method (typescript)
4. contract.view_method_name() -> Property 'view_method_name' does not exist on type 'Contract'

**Expected behavior**
Bind methods to contract instance + autocomplete these methods

**Screenshots**

<img width="993" alt="Screenshot 2021-11-06 at 23 12 48" src="https://user-images.githubusercontent.com/49167406/140622651-4dc65dba-4917-4fa9-8ee6-96bb77c9cc93.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [0.43.1]

**Comment by volovyk-s** [comment]
Hey @modagavr , please check this example to see how you can achieve desired behaviour: https://github.com/near-examples/guest-book/blob/b0458dbb4a9fcc5efe6d32986dd3ff9304e74034/src/index.js

**Comment by ryancwalsh** [comment]
@volovyk-s I don't think your link answers the question (and so I think this issue should be reopened). Your link points to a JS file. I have the same question as @modagavr , which is about TypeScript. Thanks.

**Comment by ryancwalsh** [comment]
@modagavr I think the suggestion at https://stackoverflow.com/a/34314764/470749 might be working for me.

I first define an "intersection type":

```
type NFT = Contract & {
  // https://stackoverflow.com/a/41385149/470749
  nft_mint: (args: any, gas: any, depositAmount: any) => Promise<any>; // TODO: specify the types instead of using 'any'
};
```

During Contract instantiation, I specify the `changeMethods` that I desire, such as `changeMethods: ['nft_mint']`.

Then later I can do something like `const result = (contract as NFT).nft_mint(...`

**Comment by willemneal** [comment]
@modagavr,  This isn't a bug, rather JS at runtime that is missing types at compile time.

In `Contract`'s constructor at runtime adds those methods, but at compile time TypeScript still sees just the `Contract` methods that are defined, so none of them.

Here is an example of how to provide type information and documentation for your contract methods:

https://github.com/AhaLabs/cra-template-near/pull/1/files#diff-3dc6936a9f6b48ec71621294f4507c173ba80fbd7ed5c11af9d900f23c40e5d3
