### ISSUE TITLE
process not defined in all environments

### ISSUE THREAD

**Issue by mattlockyer** [near/near-api-js#737]
_**Describe the bug**_ I use NAJ in cloudflare workers and there is not `process` and of course no `process.env` so the following code throws errors:

[https://github.com/near/near-api-js/blob/689705926fe437b8d8671d72e77148228c895992/lib/utils/errors.js#L31](https://github.com/near/near-api-js/blob/689705926fe437b8d8671d72e77148228c895992/lib/utils/errors.js#L31)

I think this was introduced with the events that were recently added?

 _**To Reproduce**_ Steps to reproduce the behavior: 1\. Run signAndSendTransaction in any environment without process.env

 _**Expected behavior**_ It works

 _**Additional context**_ I recommend checking ALSO if `process` is defined first, then checking `process.env` so that envs without process defined can still use these methods.

**Comment by esaminu** [comment]
Hey @mattlockyer, thanks for reporting! Can I get some more info about how you setup `near-api-js` on a cloudflare worker? We'd like to repro this to decide how to proceed 🙂

**Comment by erditkurteshiSQA** [comment]
Hey @mattlockyer, a kind reminder for the comment above. Thank you.

**Comment by chadoh** [comment]
You can also just try using v1.1.0 in a browser, since `process` is not defined there.

Automated tests should be able to catch this, no?
