### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by kulame** [near/near-api-js#738]
**Describe the bug**
i try to connect by 
```typescript
this.near = await connect(this.config);
```
the config data is 
```typescript
{networkId: 'testnet', nodeUrl: 'https://rpc.testnet.near.org', contractName: 'vote', walletUrl: 'https://wallet.testnet.near.org', helperUrl: 'https://helper.testnet.near.org'}
```

but it show the error 
```typescript
index.js:12 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:12)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/base-x/src/index.js (index.js:8)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/bs58/index.js (index.js:1)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/borsh/lib/index.js (index.js:33)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/near-api-js/lib/utils/serialize.js (serialize.js:3)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
node_modules/safe-buffer/index.js @ index.js:12
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/base-x/src/index.js @ index.js:8
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/bs58/index.js @ index.js:1
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/borsh/lib/index.js @ index.js:33
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/utils/serialize.js @ serialize.js:3
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/utils/key_pair.js @ key_pair.js:8
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/key_stores/in_memory_key_store.js @ in_memory_key_store.js:5
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/key_stores/browser-index.js @ browser-index.js:7
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/browser-index.js @ browser-index.js:26
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
(匿名) @ dep:near-api-js:1
```

**Expected behavior**
get the connection object

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Version [20.04]

**Additional context**

**Comment by volovyk-s** [comment]
@kulame can you try to use a valid contract id in your config? Like `nameofyourcontract.testnet`.

**Comment by kulame** [comment]
@volovyk-s  it also failed.
index.js:12 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:12)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/base-x/src/index.js (index.js:8)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/bs58/index.js (index.js:1)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/borsh/lib/index.js (index.js:33)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
    at node_modules/near-api-js/lib/utils/serialize.js (serialize.js:3)
    at __require2 (chunk-VPFHXPC5.js?v=e4e921b6:36)
node_modules/safe-buffer/index.js @ index.js:12
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/base-x/src/index.js @ index.js:8
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/bs58/index.js @ index.js:1
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/borsh/lib/index.js @ index.js:33
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/utils/serialize.js @ serialize.js:3
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/utils/key_pair.js @ key_pair.js:8
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/key_stores/in_memory_key_store.js @ in_memory_key_store.js:5
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/key_stores/browser-index.js @ browser-index.js:7
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
node_modules/near-api-js/lib/browser-index.js @ browser-index.js:26
__require2 @ chunk-VPFHXPC5.js?v=e4e921b6:36
(匿名) @ dep:near-api-js:1

**Comment by volovyk-s** [comment]
@kulame consider checking out examples. Please, provide the whole code snippet of it will not help.

**Comment by kulame** [comment]
@volovyk-s this is my repo.

https://github.com/kulame/voteapp

**Comment by volovyk-s** [comment]
@kulame please, try to localize your problem in a short code snippet and post it in `dev-support` channel in out Discord server: https://discord.com/invite/UY9Xf2k or `Dev Telegram` channel: https://t.me/neardev
