### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] calling a contract method

### ISSUE THREAD

**Issue by lau-bin** [near/near-api-js#739]
After creating a contract for an user with "new nearAPI.Contract()"
Im calling a method in the contract like this:
```
let response = await user1Contract["new"]({        
  args: {        
    owner_id:ownerAcc.accountId (its a string, also tried with a literal string to be sure)        
  },        
  gas: GAS_NORMAL(its also a string but i also tried with an integer)        
})        
console.log("Response: " + response)
 ```

Im getting the error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Account

**Expected behavior**
Call the method in the contract with my args

**Screenshots**

**Desktop (please complete the following information):**
 Linux using nearcore localnet
 Running the api with node version v14.17.6
 Using Nearcore at commit: 6be9bec9e754997ed6a121f53a79e15c5f5d7da3

**Comment by volovyk-s** [comment]
@lau-bin please, create a short working snippet with described problem, post it on StackOverflow and then post it in `dev-support` channel in our Discord: https://discord.com/invite/UY9Xf2k
