### ISSUE TITLE
When use as ES module GLOBAL not defined

### ISSUE THREAD

**Issue by anbork** [near/near-api-js#743]
I fixed importing cjs in my vite.js app, but when I try working wit SSR (it working on cjs) it falls on `global.fetch` inside connect.ts. Is it possible to rewrite it? The problem is `global` is not defined.
 [https://github.com/near/near-api-js/blob/ea4d3624c87518ab4661f850f9752986dbe78fca/esm/connect.js#L29](https://github.com/near/near-api-js/blob/ea4d3624c87518ab4661f850f9752986dbe78fca/esm/connect.js#L29)

**Comment by volovyk-s** [comment]
@tonborzenko we had a similar issue in Borsh JS.
https://github.com/near/borsh-js/pull/40
Please, create a PR if it will work for you.

**Comment by rhythnic** [comment]
@tonborzenko I'm not able to replicate `global` is undefined in connect.ts when working with Vite's SSR setup.  Are you getting the error on the browser or the server?  Vite's example SSR server [serves the static assets from the client build](https://github.com/vitejs/vite/blob/2762a0e7f0a599ced2c25c9d2baf06ec99ad8cfb/packages/playground/ssr-vue/server.js#L48).  The client build should be using browser-index.ts and browser-connect.ts.  Although that's for prod.  I don't know what the vite createServer middleware is doing, but it's working for me.

Using `near-api-js` in SSR also requires not using `BrowserLocalStorageKeyStore` or `WalletConnection` when rendering a route on the server.

**Comment by rhythnic** [comment]
I removed my previous comment because it was wrong.

I'm getting this error too, not on SSR, but a Vite single page application.

```
index.js:36 Uncaught ReferenceError: global is not defined
    at node_modules/borsh/lib/index.js (index.js:36:22)
    at node_modules/near-api-js/lib/utils/serialize.js (serialize.js:3:15)
    at node_modules/near-api-js/lib/utils/key_pair.js (key_pair.js:8:21)
    at node_modules/near-api-js/lib/key_stores/in_memory_key_store.js (in_memory_key_store.js:5:20)
    at node_modules/near-api-js/lib/key_stores/browser-index.js (browser-index.js:7:31)
```

As a workaround I'm adding this to `vite.config.ts`.  Sign-in is still working.
```
define: {
  global: {}
}
```
