### ISSUE TITLE
Handle the new seat allocation algorithm

### ISSUE THREAD

**Issue by frol** [near/near-api-js#744]
https://github.com/near/near-cli/issues/895 (cc @nikurt):

> `nearcore 1.23` is scheduled to be released on Dec 13th.
> After the protocol upgrade takes place, every validator will have exactly 1 seat, and the seat price calculation will be much simpler.
> 
> Seat price can be defined in two ways:
> 1. minimal staked amount of the active validators.
> 2. minimal amount that gives a new validator a seat.
> I think the second option is more informative in case there are free validator seats.
> 
> Would it be possible to make these changes available at roughly the same time as the protocol upgrade happens next week?

We should update the [`findSeatPrice` implementation](https://github.com/near/near-api-js/blob/01b61cb8d2a1c342fec4017355061f053500548d/src/validators.ts#L11) in order to unblock near-cli (https://github.com/near/near-cli/issues/895) and near-explorer (https://github.com/near/near-explorer/issues/797)

@volovyk-s Do you have the capacity to work on it this week?

**Comment by volovyk-s** [comment]
@frol @nikurt looks like it's not possible to do it in a non-breaking way. Current version of `findSeatPrice()` is calculating result from `validators` call result. And the new one will just return the field from `EXPERIMANTAL_genesis_config`. 
```javascript
export function findSeatPrice(validators: (CurrentEpochValidatorInfo | NextEpochValidatorInfo)[], numSeats: number): BN {...}
```

**Comment by nikurt** [comment]
> the new one will just return the field from EXPERIMANTAL_genesis_config

Not sure what you mean. Genesis config doesn't have seat price.
