### ISSUE TITLE
treat `window` and `Buffer` more gracefully so that using Gatsby is possible

### ISSUE THREAD

**Issue by ryancwalsh** [near/near-api-js#747]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy a frontend for NEAR using Gatsby, but I'm blocked because near-api-js assumes `window` will always be defined.

```
failed Building static HTML for pages - 1.293s

 ERROR #95312 

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  32 |      * @param prefix defaults to `near-api-js:keystore:`
  33 |      */
> 34 |     constructor(localStorage = window.localStorage, prefix = LOCAL_STORAGE_KEY_PREFIX) {
     | ^
  35 |         super();
  36 |         this.localStorage = localStorage;
  37 |         this.prefix = prefix;


  WebpackError: ReferenceError: window is not defined
  
  - browser_local_storage_key_store.js:34 
    [gatsby-starter-default]/[near-api-js]/lib/key_stores/browser_local_storage_key_store.js:34:1
  
  - near.ts:23 
    gatsby-starter-default/src/services/near.ts:23:13

```

This breaks the Gatsby build. It's probably simple to edit near-api-js to use `window` only when it exists.

A similar problem (with this [hacky workaround](https://stackoverflow.com/a/70296962/470749)) relates to Buffer:

```
Uncaught (in promise) ReferenceError: Buffer is not defined
    at bytesJsonStringify (webpack-internal:///./node_modules/near-api-js/lib/account.js:27)
    at ConnectedWalletAccount.viewFunction (webpack-internal:///./node_modules/near-api-js/lib/account.js:365)
    at eval (webpack-internal:///./node_modules/near-api-js/lib/contract.js:73)
    at Contract.getCommitments (webpack-internal:///./node_modules/near-api-js/lib/contract.js:15)
    at _callee$ (webpack-internal:///./src/services/near.ts:80)
```

near-api-js probably could similarly be edited to handle Buffer more gracefully. 

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Additional context**

**Comment by volovyk-s** [comment]
Thanks, @ryancwalsh ! That needs to be fixed. Do you think you can create a PR?

**Comment by ryancwalsh** [comment]
Hey @volovyk-s , I'm curious whether anyone has made progress in the direction that @MaximusHaximus described at https://github.com/near/near-api-js/pull/748. Where can I track that?

If not, can you please reopen #747 because I keep running into this problem (not just with Gatsby but also with Next.js getServerSideProps).

I see also other people running into it at https://github.com/near/near-api-js/issues/757, and my teammate Hiba on NF Education team said she had this problem in Vue yesterday, too.

Thanks!

**Comment by chadoh** [comment]
@ryancwalsh I created #801 to workaround the lingering reference to `window` when initializing a `WalletConnection`, which was the big blocker for me when building a Gatsby site. I'd love to see the suggestions from @MaximusHaximus in #748, but until then, hopefully this is an acceptable approach.

Use it now by updating your `package.json` with:

    "near-api-js": "AhaLabs/near-api-js#1.0.1"

**Comment by ryancwalsh** [comment]
@chadoh Cool, thanks for sending.
