### ISSUE TITLE
Can not get proper responce from new RPC server (https://testnet.rpc.near.dev)

### ISSUE THREAD

**Issue by volovyk-s** [near/near-api-js#750]
**Description:**
Examples ([1](https://github.com/near/near-api-js/blob/master/examples/cookbook/api-keys/near-connection.js) and [2](https://github.com/near/near-api-js/blob/master/examples/cookbook/api-keys/provider-example.js)) of API Keys usage stopped working. They return results when I'm using a standard RPC server (https://rpc.testnet.near.org), but throw errors on a new one that supports API Keys (https://testnet.rpc.near.dev).

**Error:**
```bash
/home/serhii/Projects/NEAR/near-api-js/examples/cookbook/node_modules/near-api-js/lib/utils/web.js:34
                throw http_errors_1.default(response.status, await response.text());
                                           ^
BadRequestError: Json deserialize error: EOF while parsing a value at line 1 column 0
    at /home/serhii/Projects/NEAR/near-api-js/examples/cookbook/node_modules/near-api-js/lib/utils/web.js:34:44
```

**To reproduce:**
Replace constants in example with and run them:
```bash
const RPC_API_ENDPOINT = 'https://testnet.rpc.near.dev';
// const RPC_API_ENDPOINT = 'https://rpc.testnet.near.org';
const API_KEY = '94e2a8aa-d64b-4078-a0bd-f3725d58f226';
```

**Comment by volovyk-s** [comment]
@MaximusHaximus not sure if it's on the JS side. Looks like the https://testnet.rpc.near.dev/ server changed its behavior.
cc @chefsale

**Comment by volovyk-s** [comment]
But at the same moment, `curl` works just fine.
```bash
curl -H 'x-api-key: 94e2a8aa-d64b-4078-a0bd-f3725d58f226' -H 'content-type: application/json' -v https://testnet.rpc.near.dev  --data '{"jsonrpc": "2.0", "id": "dontcare", "method": "status", "params": []}'
```

**Comment by volovyk-s** [comment]
Reproducible in this JS snippet:
```javascript
var fetch = require('node-fetch');

const RPC_SERVER = `https://testnet.rpc.near.dev`;
// const RPC_SERVER = `https://rpc.testnet.near.org`;

async function executeFetch() {
    const response = await fetch(RPC_SERVER, {
        method: 'POST',
        headers: {
            'x-api-key': '94e2a8aa-d64b-4078-a0bd-f3725d58f226',
            'content-type': 'application/json',
            'Content-Type': 'application/json; charset=UTF-8'
        },
        body: JSON.stringify({ "jsonrpc": "2.0", "id": "dontcare", "method": "status", "params": [] })
    });
    if (!response.ok) {
        console.log(response);
        console.log(response.status, await response.text());
        return;
    }
    console.log(JSON.stringify(await response.json()));
}

executeFetch();
```

**Comment by volovyk-s** [comment]
But when I'm using `request` instead of `node-fetch` it works just fine:
```javascript
var request = require('request');

const RPC_SERVER = `https://testnet.rpc.near.dev`;
// const RPC_SERVER = `https://rpc.testnet.near.org`;

var headers = {
    'x-api-key': '94e2a8aa-d64b-4078-a0bd-f3725d58f226',
    'content-type': 'application/json'
};

var dataString = '{"jsonrpc": "2.0", "id": "dontcare", "method": "status", "params": []}';

var options = {
    url: RPC_SERVER,
    method: 'POST',
    headers: headers,
    body: dataString
};

function callback(error, response, body) {
    if (!error && response.statusCode == 200) {
        console.log(body);
    }
}
request(options, callback);
```

**Comment by volovyk-s** [comment]
Ok, so the reason why [this](https://github.com/near/near-api-js/issues/750#issuecomment-993489345) snippet does not work is headers.
```bash
'Content-Type': 'application/json; charset=UTF-8'
```
After deletion of this line first example works.

**Comment by volovyk-s** [comment]
So, if on the JS side we will change
```javascript
headers: { ...connectionInfo.headers, 'Content-Type': 'application/json; charset=UTF-8' }
```
to
```javascript
headers: { ...connectionInfo.headers, 'content-type': 'application/json' }
```
on line
https://github.com/near/near-api-js/blob/master/src/utils/web.ts#L33
everything will work.

But it means that old versions of `near-api-js` will not be able to communicate with new RPC server. So, let's revert this change on the server side. cc @chefsale

**Comment by volovyk-s** [comment]
Curl:
```bash
curl -X POST https://testnet.rpc.near.dev -H "x-api-key: 94e2a8aa-d64b-4078-a0bd-f3725d58f226" -H "application/json; charset=UTF-8" -d "{\"jsonrpc\": \"2.0\", \"id\": \"dontcare\", \"method\": \"status\", \"params\": []}"
```
with `charset=UTF-8` will give us `Content type error`.

**Comment by chefsale** [comment]
Yes, I think we can drop it. Either-ways it will not work on older versions as it will not have API keys implemented. I think we can leave it like this. Not sure to be honest why do we need this in the first place.

**Comment by chefsale** [comment]
Also it seems the version of actix doesn't allow the charset thing, but just application.json, so one more reason to stick with it.

**Comment by volovyk-s** [comment]
Response content type in both old and new servers is `'content-type': [ 'application/json' ]`. So it should not be a breaking change.
