### ISSUE TITLE
clearer names for parseNearAmount and formatNearAmount?

### ISSUE THREAD

**Issue by ryancwalsh** [near/near-api-js#778]
This is just a minor naming suggestion (I'm a new hire on NEAR Foundation's Education team).

At [https://github.com/near/near-api-js/blob/master/examples/quick-reference.md#near--yoctonear](https://github.com/near/near-api-js/blob/master/examples/quick-reference.md#near--yoctonear) I see:

```js
 const 

 { utils } 

 = nearAPI;
 // converts NEAR amount into yoctoNEAR (10^-24)
 const amountInYocto = utils.format.parseNearAmount("1");
 // converts yoctoNEAR (10^-24) amount into NEAR
 const amountInNEAR = utils.format.formatNearAmount("1000000000000000000000000");
 ```

Personally, I feel like `parseNearAmount` and `formatNearAmount` aren't clear enough method names. 

(I'll need to come look at these examples every time because I won't be able to remember which is which.)

Maybe we could rename them or add aliases for them, such as `convertNearToYoctonear` and `convertYoctonearToNear` (which makes the direction explicit)?

Or I'm open to other ideas. I'd be happy to offer a PR if others agree with my general request.

**Comment by willemneal** [comment]
Check out https://www.npmjs.com/package/near-units

**Comment by ryancwalsh** [comment]
Awesome. Thanks, @willemneal !

**Comment by vikinatora** [comment]
Hi @ryancwalsh, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this issue seems no longer relevant. Please let me know if that's not the case; otherwise, I'll proceed to close the issue in 5 days.

**Comment by vikinatora** [comment]
Closing as issue isn't relevant anymore.
