### ISSUE TITLE
can not create wallet using createAccount

### ISSUE THREAD

**Issue by shyamin** [near/near-api-js#786]
Can not sign transactions for account ldx.testnet on network testnet, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/home/sysadmin/.near-credentials), UnencryptedFileSystemKeyStore(/home/sysadmin/neardev)))

i need to create sub wallet according to my main account.
 First i create connection in testnet and create key store using credentials directory
 then load the main account
 after call the createAccount function

but always i got bellow error 

Can not sign transactions for account ldx.testnet on network testnet, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/home/sysadmin/.near-credentials), UnencryptedFileSystemKeyStore(/home/sysadmin/neardev)))

please help me to solve this issue
 !<span class="error">[Screenshot from 2022-02-02 18-20-56]</span>([https://user-images.githubusercontent.com/24448608/152157201-32eaa673-4338-40c8-854c-ed2bcf76620a.png](https://user-images.githubusercontent.com/24448608/152157201-32eaa673-4338-40c8-854c-ed2bcf76620a.png))

**Comment by gtsonevv** [comment]
@frol, looks like the added key is invalid or missing. What do you think?

**Comment by vikinatora** [comment]
Closing as @shyamin hasn't responded in a month.
