### ISSUE TITLE
(node:15412) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'keyStore' of undefined

### ISSUE THREAD

**Issue by Alibek23** [near/near-api-js#790]
`const keyStore = null; // GetLocalnet();

const config = 

 { networkId: "example.testnet", keyStore, // optional if not signing transactions nodeUrl: "https://rpc.testnet.near.org", walletUrl: "https://wallet.testnet.near.org", helperUrl: "https://helper.testnet.near.org", explorerUrl: "https://explorer.testnet.near.org", } 

;
 const near = await connect(config);

return near;`

where to get the keyStore?

**Comment by marcinbodnar** [comment]
Checked. No longer an issue.
