### ISSUE TITLE
Why do you store the dist (lib folder) in the git? 

### ISSUE THREAD

**Issue by frolovdev** [near/near-api-js#796]
***Is your feature request related to a problem? Please describe.***
 You store the result of compilation on git. Is there any reason for this

***Describe the solution you'd like***

Add a dist to gitignore, rebuild the dist on every prerelease script

***Describe alternatives you've considered***
 N/A

**Comment by willemneal** [comment]
My guess is that early on it meant that you could depend on the repo as a git dependency.

**Comment by frolovdev** [comment]
> My guess is that early on it meant that you could depend on the repo as a git dependency.

Thanks for the answer @willemneal , so right now it's a redundant behavior and we can take a step ahead to remove it?

**Comment by janewang** [comment]
This is fixed by this commit in .gitignore. Closing.
