### ISSUE TITLE
Introduce any bundler

### ISSUE THREAD

**Issue by frolovdev** [near/near-api-js#798]
**Is your feature request related to a problem? Please describe.** Javascript ecosystem contains a lot of environments and module variants.

The main targets are:

*   node with native ESM. You will support cutting-edge users, which will have a passion for esm modules.
*   node with common js
*   browsers with esm (which will be handled by bundler on consumer side). To make it treeshackable.

To support such builds it's better to use a bundler (e.g. rollup).

**Describe the solution you'd like** Introduce rollup and make different build for different envs

{ "main": "dist/index.js", "module": "dist/index.esm.js", "browser":

 { "./dist/index.js": "./dist/index.browser.js", "./dist/index.esm.js": "./dist/index.browser.esm.js" } 

}

**Describe alternatives you've considered**

*   webpack - but it's much more convenient for applications
*   esbuild - not so stable as proposed solution
*   ....

**Additional context**

Also we need to decide which versions of browser we target to separate browser bundle

**Comment by VanishMax** [comment]
Agree with @frolovdev. I wanted to use the Near API in the React project built with Vite, and it is not currently possible. Sadly
