### ISSUE TITLE
possible typo in quick reference docs

### ISSUE THREAD

**Issue by il3ven** [near/near-api-js#799]
***Describe the bug***
 The quick reference docs includes a section about <span class="error">[*loading a contract*]</span>([https://github.com/near/near-api-js/blob/master/examples/quick-reference.md#load-contract](https://github.com/near/near-api-js/blob/master/examples/quick-reference.md#load-contract)). In the sub-section about loading a contract from a wallet there appears to be a typo. 

The current code is as follows,
 ```js
 const contract = new nearAPI.Contract(
 wallet.account(), // the account object that is connecting
 "example-contract.testnet",

 { // name of contract you're connecting to viewMethods: ["getMessages"], // view methods do not change state but usually return a value changeMethods: ["addMessage"], // change methods modify state sender: wallet.Account(), // account object to initialize and sign transactions. } 

);
 ```

***Expected behavior***
 I believe it should be `wallet.account` with a smaller case.
 ```diff

*   sender: wallet.Account(), // account object to initialize and sign transactions.
     + sender: wallet.account(), // account object to initialize and sign transactions.
     ```

***Additional context***
 I recently started developing on Near. I maybe wrong but I am using `wallet.account()` in my code and it seems to work.

**Comment by il3ven** [comment]
You are right. I just checked the source code. Should I create a quick PR to fix the docs?

https://github.com/near/near-api-js/blob/e92725352a5ad33db7ba97f4d181da44af88267f/src/contract.ts#L31-L45

**Comment by willemneal** [comment]
Definitely!
