### ISSUE TITLE
WalletConnection calling asynchronous method from synchronous constructor

### ISSUE THREAD

**Issue by miancadonc** [near/near-api-js#817]
_**Describe the bug**_ Constructor for `WalletConnection` calls `this._completeSignInWithAccessKey()` which is marked as asynchronous. If we initialize a `WalletConnection` in the recommended way,

 near = await connect(nearConfig);
 wallet = new WalletConnection(near);

`wallet` is not ready for use. Specifically, `_completeSignInWithAccessKey()` modifies browser history state and creates a race condition if client code tries to do the same.

 _**To Reproduce**_ Steps to reproduce the behavior:

 near = await connect(nearConfig);
 wallet = new WalletConnection(near);
 window.history.pushState(null, '', '/');

 _**Expected behavior**_ Expected result was to see the url modified according to `pushState()`, but we actually see unpredictable url results

 _**Desktop:**_ 

*   OS: macOS
*   Version 12.2.1

**Comment by aka-toxa** [comment]
hey 

Just created this PR https://github.com/near/near-api-js/pull/842

**Comment by janewang** [comment]
Thanks for the PR @aka-toxa!
