### ISSUE TITLE
Remove usage of `window` in WalletConnection class constructor

### ISSUE THREAD

**Issue by sinnrrr** [near/near-api-js#824]
***Describe the bug***
 Unable to use in Node.js environment due to direct reference to the window object. Getting `window is not defined` error. Link to <span class="error">[the cause of the issue]</span>([https://github.com/near/near-api-js/blob/e92725352a5ad33db7ba97f4d181da44af88267f/lib/wallet-account.js#L43](https://github.com/near/near-api-js/blob/e92725352a5ad33db7ba97f4d181da44af88267f/lib/wallet-account.js#L43)).

***To Reproduce***
 `new WalletConnection(nearClient, null)`

***Expected behavior***
 [https://github.com/near/near-api-js/issues/747](https://github.com/near/near-api-js/issues/747)
 [https://github.com/AhaLabs/near-api-js/pull/12](https://github.com/AhaLabs/near-api-js/pull/12)

***Screenshots***
 <img width="693" alt="image" src="https://user-images.githubusercontent.com/25615887/159305189-03e7a55e-e2e5-4a1c-8c99-6874bd11ebf7.png">

***Desktop:***

*   OS: MacOS 11
*   Package version: 0.44.2

***Additional context***
 No additional context.

**Comment by hindams** [comment]
+1 for removing window from the library.

**Comment by searchableguy** [comment]
Faced the same issue. It's almost impossible to polyfill the library as well because it depends on a gigantic set of browser only APIs.

**Comment by GrinOleksandr** [comment]
why this issue is closed? this bug is still appears, the platform can't be used on backend!
