### ISSUE TITLE
View function should allow for finality option instead of pinning to optimistic

### ISSUE THREAD

**Issue by willemneal** [near/near-api-js#836]
[https://github.com/near/near-api-js/blob/6f83d39f47624b4223746c0d27d10f78471575f7/src/account.ts#L516-L531](https://github.com/near/near-api-js/blob/6f83d39f47624b4223746c0d27d10f78471575f7/src/account.ts#L516-L531)

**Comment by marcinbodnar** [comment]
No longer an issue. `finality` is available with `options.blockQuery` for `viewFunctionV1` and with `blockQuery` param for `viewFunctionV2`
