### ISSUE TITLE
In 0.44.2 'headers' property is required in ConnectConfig

### ISSUE THREAD

**Issue by piontkovsk11andre1** [near/near-api-js#839]
After switching to 0.44.2 got error for `connect` function.

`Property 'headers' is missing in type '

 { ... } 

' but required in type 'ConnectConfig'.`

near-api-js/lib/near.d.ts:

 /**

*   NEAR RPC API headers. Can be used to pass API KEY and other parameters.
*   @see {@link JsonRpcProvider.JsonRpcProvider | JsonRpcProvider} 

     */
     headers: 

     { [key: string]: string | number; } 

    ;

It's neither described in [the connect module documentation](https://near.github.io/near-api-js/modules/connect.html) nor [ConnectConfig type description](https://near.github.io/near-api-js/interfaces/connect.connectconfig.html).

**Comment by ailisp** [comment]
Pass to Application Team

**Comment by marcinbodnar** [comment]
Fixed in https://github.com/near/near-api-js/pull/939
