### ISSUE TITLE
Can you make authorization in a new window as a parameter of the requestSignIn function?

### ISSUE THREAD

**Issue by Ellweb3** [near/near-api-js#840]
_**Is your feature request related to a problem? Please describe.**_ Yes. When developing plugins for other sites, it often fails to do authorization due to the fact that the near site cannot open in a frame.

 _**Describe the solution you'd like**_ 

Make an option to open authorization in a new window like option parametr for `wallet.requestSignIn` like `

 {"options": "newWindow": true} 

`or a new function`requestSignInViaNewWindow`.

 _**Describe alternatives you've considered**_ The alternative can be changed in the standard command function `window.location.assign(newUrl.toString())` to `window.open(newUrl.toString(), "_parent")`, but this may cause other problems

 _**Additional context**_ [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/95847507/162766857-6c86bb7c-062f-4cbd-a58a-373536d48bbc.png)</span>](https://user-images.githubusercontent.com/95847507/162766857-6c86bb7c-062f-4cbd-a58a-373536d48bbc.png)

**Comment by vikinatora** [comment]
Will be resolved by #1260
