### ISSUE TITLE
how can i get the transaction history

### ISSUE THREAD

**Issue by polariseye** [near/near-api-js#846]
**Is your feature request related to a problem? Please describe.**
i am developing near wallet .and i can not found the api to get transaction history.

**Describe the solution you'd like**
add the transaction history api

**Comment by andy-haynes** [comment]
@polariseye the NEAR indexer is responsible for querying transaction history, it's not a part of `near-api-js`. There are public indexers available for testing but for production use in a wallet application please see https://near-indexers.io/
