### ISSUE TITLE
Remove legacy adapter in provider.ts for old transaction results

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-api-js#86]
Once 0.4.0 is merged to `master` in `nearcore` we can remove some legacy code, e.g. `adaptTransactionResult`, `fixLegacyBasicExecutionOutcomeFailure`, and `mapLegacyTransactionLog`.

**Comment by vgrichina** [comment]
@evgenykuzyakov looks like this can be fixed already, right?

**Comment by mehtaphysical** [comment]
Seems like this is already fixed
