### ISSUE TITLE
Add Warning and Docs for Deleting Account to Transfer NFTs and FTs

### ISSUE THREAD

**Issue by BenKurrek** [near/near-api-js#882]
When an account is deleted and funds are sent to the beneficiary, we should mention that "Deleting an account does not automatically transfer NFTs and FT to the beneficiary address. Ensure to transfer assets before deleting"

This could live as a comment / message for the interface and or could actually `console.log` such that if someone didn't know that, they could quickly re-create the account and recover the assets.

**Comment by judith-Near** [comment]
[addressed by this PR ](https://github.com/near/near-api-js/pull/883)

**Comment by vikinatora** [comment]
Resolved by #883
