### ISSUE TITLE
Unable to use serialize function on testnet env

### ISSUE THREAD

**Issue by igorms-pro** [near/near-api-js#887]
**Describe the bug** I am getting crazy with the `nearAPI.utils.serialize.serialize`. I am trying to follow the steps for `createTransaction` [here](https://docs.near.org/docs/tutorials/create-transactions). Since few hours, ` nearAPI.utils.serialize.serialize` returns an error:

 ndex.js:323 Uncaught (in promise) Error: Class String is missing in schema: publicKey
 at serializeStruct (index.js:323:15)
 at serializeField (index.js:306:13)
 at index.js:327:13
 at Array.map (<anonymous>)
 at serializeStruct (index.js:326:29)
 at Object.serialize (index.js:349:5)
 at bbt (<span class="error">[id]</span>.vue:101:1)

I am using vue3 with nuxt3 framework, I thought it can be a bad config so I tried to clone this [repo](https://github.com/near-examples/transaction-examples) , and guess what, same error.

**Desktop (please complete the following information):** **- OS: MacOS Monterey 124** **- Version near-api-js 0.44.2**

Do you have any idea on what is causing this issue?

**Comment by esaminu** [comment]
Hi @igorms-pro I am unable to reproduce this on [the transaction-examples repo](https://github.com/near-examples/transaction-examples). The error is a serialization error being thrown by [near/borsh-js](https://github.com/near/borsh-js) when it attempts to serialize your transaction. It happens [here](https://github.com/near/borsh-js/blob/6db74764cedb88097bd6d5636407f0b3481fba4c/borsh-ts/index.ts#L322) where your transaction is being passed in as `obj` when you call `nearAPI.utils.serialize.serialize`

Please make sure you are creating the transaction correctly using `createTransaction` and check the arguments. Feel free to reopen providing specific values you are passing to `createTransaction` if you'd like more assistance! 🙂

**Comment by igorms-pro** [comment]
> Hi @igorms-pro I am unable to reproduce this on [the transaction-examples repo](https://github.com/near-examples/transaction-examples). The error is a serialization error being thrown by [near/borsh-js](https://github.com/near/borsh-js) when it attempts to serialize your transaction. It happens [here](https://github.com/near/borsh-js/blob/6db74764cedb88097bd6d5636407f0b3481fba4c/borsh-ts/index.ts#L322) where your transaction is being passed in as `obj` when you call `nearAPI.utils.serialize.serialize`
> 
> Please make sure you are creating the transaction correctly using `createTransaction` and check the arguments. Feel free to reopen providing specific values you are passing to `createTransaction` if you'd like more assistance! 🙂

Thx a lot, I was doing something wrong.
Not I am facing an error when tried to make a deposit
```
    const actions = [
        nearAPI.transactions.functionCall(
          'storage_deposit',
          Buffer.from(JSON.stringify({})),
          10000000000000,
          nearAPI.utils.format.parseNearAmount('0.1')
        ),
      ]
      ```
    I have error when I deposit 0.1N. I dont know how to do it
