### ISSUE TITLE
EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ductridev** [near/near-api-js#894]
**Describe the bug** EventEmitter memory leak detected.

**To Reproduce** Steps to reproduce the behavior: click on Connect Wallet button and call this code:

 const keyStore = new keyStores.BrowserLocalStorageKeyStore(); 
 window.near = await NEARconnect(config); 
 window.NEARwallet = new WalletConnection(window.near, "dag_crypto_bridge"); 
 if (!window.NEARwallet.isSignedIn()) 

 { window.NEARwallet.requestSignIn(); } 

 else 

 { setBuyerAddress(window.NEARwallet.getAccountId()); let senderNEARAccount = await window.near.account(window.NEARwallet.getAccountId()); window.senderNEARAccount = senderNEARAccount; } 

**Expected behavior** It should open new tabs if users do not log in, and return near address if the user logged in.

**Screenshots** [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/49811496/179267374-802f096e-32bf-42af-8468-d6cd064cacac.png)</span>](https://user-images.githubusercontent.com/49811496/179267374-802f096e-32bf-42af-8468-d6cd064cacac.png)

**Desktop (please complete the following information):**

*   OS: Windows 10 Build 19044.1826
*   Version: near@0.45.1

**Comment by gtsonevv** [comment]
Hey @ductridev @frol, I wasn't able to reproduce this issue.

**Comment by vikinatora** [comment]
Closing as issuer doesn't respond and issue couldn't be reproducer
