### ISSUE TITLE
Inconsistent JSON serialization of BigInt usage

### ISSUE THREAD

**Issue by austinabell** [near/near-api-js#919]
This is more a question about why the `bn.js` library is used for big integers. Unclear why [`BigInt` builtin](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) isn't used/supported.

The main footgun right now is that `bn.js` JSON serializes integers as hex, which is inconsistent from how they are serialized in other tooling. The pattern seems to be that big integers are serialized as stringified decimal (which I don't agree with but is what is used mainly), so it seems like this could lead to hidden bugs where the decimal is interpreted as hex.

**Comment by mgild** [comment]
In the same vein, why do `i128` fields only accept `number`?  They should accept either of the above suggestions.

**Comment by vikinatora** [comment]
Will be resolved by #1223

**Comment by flmel** [comment]
Closed by https://github.com/near/near-api-js/pull/1223
